// GENERATED by scripts/gen_query_error_codes.py. Do not edit by hand.

/// Every parser, tokenizer, validator and path error (#2365). A code plus
/// the words it quotes ([argNames]) is what the UI localizes; the English
/// text below is the engine's own message.
enum QueryErrorCode {
  unterminatedQuote([]),
  unexpectedCharacter(['text']),
  unexpectedToken(['text']),
  expectedCloseParen([]),
  expectedCloseBracket([]),
  expectedOpenBracketAfterIn([]),
  expectedAnd([]),
  expectedOperator([]),
  expectedConditionOrText([]),
  expectedName([]),
  expectedDate([]),
  expectedDateValue([]),
  expectedValue([]),
  expectedNumber([]),
  expectedText([]),
  expectedBool([]),
  emptyText([]),
  emptyList([]),
  emptyGroup([]),
  emptyPath([]),
  notSingleDay(['text']),
  notADate(['text']),
  openEndedDate(['text', 'field', 'symbol', 'day']),
  unknownUnit(['unit']),
  noUnitAllowed(['field']),
  wrongUnitDimension(['unit', 'dimension']),
  wrongUnitForField(['unit', 'dimension', 'field']),
  decimalComma([]),
  scopeNeedsRelationQuoted(['path']),
  scopeNeedsRelation(['path']),
  relationNeedsRefOp(['path']),
  relationOpNotAllowed(['op']),
  opNotForFieldQuoted(['op', 'field']),
  opNotForField(['op', 'field']),
  noneAmbiguous(['field']),
  noRefNamed(['relation', 'text']),
  notEnumValue(['text', 'field']),
  unknownField(['name']),
  fieldNotPath(['name', 'next']),
  tooManyHops(['max']),
  pathTooLong(['max']),
  textNotSearchable(['table']),
  expectsReference(['name']),
  expectsReferences(['name']),
  betweenNeedsTwo([]),
  inNeedsList([]),
  expectsNumber(['field']),
  outOfRange(['field']),
  expectsText(['field']),
  expectsBool(['field']),
  expectsEnumValue(['field']),
  expectsSingleDay(['field']),
  expectsDate(['field']);

  const QueryErrorCode(this.argNames);

  /// The args the message quotes, in the order they appear.
  final List<String> argNames;
}

/// The English text of [code] with [args] substituted: the engine's message
/// for logs and tests. The UI shows `describeQueryError` instead.
String englishQueryMessage(QueryErrorCode code, Map<String, String> args) {
  String a(String name) => args[name] ?? '';
  switch (code) {
    case QueryErrorCode.unterminatedQuote:
      return 'unterminated quote';
    case QueryErrorCode.unexpectedCharacter:
      return 'unexpected character "${a('text')}"';
    case QueryErrorCode.unexpectedToken:
      return 'unexpected "${a('text')}"';
    case QueryErrorCode.expectedCloseParen:
      return 'expected ")"';
    case QueryErrorCode.expectedCloseBracket:
      return 'expected "]"';
    case QueryErrorCode.expectedOpenBracketAfterIn:
      return 'expected "[" after "in"';
    case QueryErrorCode.expectedAnd:
      return 'expected "and"';
    case QueryErrorCode.expectedOperator:
      return 'expected an operator';
    case QueryErrorCode.expectedConditionOrText:
      return 'expected a condition or text';
    case QueryErrorCode.expectedName:
      return 'expected a name';
    case QueryErrorCode.expectedDate:
      return 'expected a date';
    case QueryErrorCode.expectedDateValue:
      return 'expected a date value';
    case QueryErrorCode.expectedValue:
      return 'expected a value';
    case QueryErrorCode.expectedNumber:
      return 'expected a number';
    case QueryErrorCode.expectedText:
      return 'expected text';
    case QueryErrorCode.expectedBool:
      return 'expected true or false';
    case QueryErrorCode.emptyText:
      return 'empty text';
    case QueryErrorCode.emptyList:
      return 'the list is empty';
    case QueryErrorCode.emptyGroup:
      return 'an empty group matches nothing';
    case QueryErrorCode.emptyPath:
      return 'empty path';
    case QueryErrorCode.notSingleDay:
      return '"${a('text')}" is not a single day';
    case QueryErrorCode.notADate:
      return '"${a('text')}" is not a date';
    case QueryErrorCode.openEndedDate:
      return '"${a('text')}" is open-ended; write ${a('field')} ${a('symbol')} ${a('day')} instead';
    case QueryErrorCode.unknownUnit:
      return 'unknown unit "${a('unit')}"';
    case QueryErrorCode.noUnitAllowed:
      return '${a('field')} takes no unit';
    case QueryErrorCode.wrongUnitDimension:
      return '"${a('unit')}" is not a ${a('dimension')} unit';
    case QueryErrorCode.wrongUnitForField:
      return '"${a('unit')}" is not a ${a('dimension')} unit; ${a('field')} is measured in ${a('dimension')}';
    case QueryErrorCode.decimalComma:
      return 'use "." for decimals, not ","';
    case QueryErrorCode.scopeNeedsRelationQuoted:
      return '"[...]" needs a relation, "${a('path')}" is a field';
    case QueryErrorCode.scopeNeedsRelation:
      return '[...] needs a relation, "${a('path')}" is a field';
    case QueryErrorCode.relationNeedsRefOp:
      return '"${a('path')}" is a relation; use =, in, :none, :any or [...]';
    case QueryErrorCode.relationOpNotAllowed:
      return '"${a('op')}" cannot be used with a relation; use =, !=, in, :none, :any or [...]';
    case QueryErrorCode.opNotForFieldQuoted:
      return '"${a('op')}" cannot be used with ${a('field')}';
    case QueryErrorCode.opNotForField:
      return '${a('op')} cannot be used with ${a('field')}';
    case QueryErrorCode.noneAmbiguous:
      return '"${a('field')}:none" is ambiguous: write "${a('field')} = none" for the value none, or "NOT ${a('field')}:any" for unrecorded';
    case QueryErrorCode.noRefNamed:
      return 'no ${a('relation')} named "${a('text')}"';
    case QueryErrorCode.notEnumValue:
      return '"${a('text')}" is not a ${a('field')} value';
    case QueryErrorCode.unknownField:
      return 'unknown field "${a('name')}"';
    case QueryErrorCode.fieldNotPath:
      return '"${a('name')}" is a field and cannot be followed by ".${a('next')}"';
    case QueryErrorCode.tooManyHops:
      return 'a query may cross at most ${a('max')} relations, counting nested groups';
    case QueryErrorCode.pathTooLong:
      return 'a path may cross at most ${a('max')} relations';
    case QueryErrorCode.textNotSearchable:
      return 'free text cannot be searched inside ${a('table')}';
    case QueryErrorCode.expectsReference:
      return '${a('name')} expects a reference';
    case QueryErrorCode.expectsReferences:
      return '${a('name')} expects references';
    case QueryErrorCode.betweenNeedsTwo:
      return 'between needs two values';
    case QueryErrorCode.inNeedsList:
      return 'in needs a list';
    case QueryErrorCode.expectsNumber:
      return '${a('field')} expects a number';
    case QueryErrorCode.outOfRange:
      return '${a('field')} value is out of range';
    case QueryErrorCode.expectsText:
      return '${a('field')} expects text';
    case QueryErrorCode.expectsBool:
      return '${a('field')} expects true or false';
    case QueryErrorCode.expectsEnumValue:
      return '${a('field')} expects one of its values';
    case QueryErrorCode.expectsSingleDay:
      return '${a('field')} expects a single day here';
    case QueryErrorCode.expectsDate:
      return '${a('field')} expects a date';
  }
}
