import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:path/path.dart' as p;

import 'package:submersion/features/media/data/services/local_bookmark_storage.dart';
import 'package:submersion/features/media/data/services/local_media_platform.dart';
import 'package:submersion/features/media/domain/entities/media_item.dart';

/// Produces and caches OS-generated poster frames for local-file videos.
///
/// On a cache miss it calls [LocalMediaPlatform.generateVideoThumbnail] and
/// stores the result on disk keyed by the source file's path + mtime + size +
/// requested dimension, so replacing the file (which changes its mtime) busts
/// the entry. Returns null when no poster can be produced, leaving the caller
/// to fall back to the raw-video placeholder.
class VideoThumbnailService {
  VideoThumbnailService({
    required LocalMediaPlatform platform,
    required LocalBookmarkStorage bookmarkStorage,
    required Future<Directory> Function() cacheDir,
  }) : _platform = platform,
       _bookmarkStorage = bookmarkStorage,
       _cacheDir = cacheDir;

  final LocalMediaPlatform _platform;
  final LocalBookmarkStorage _bookmarkStorage;
  final Future<Directory> Function() _cacheDir;
  Directory? _resolvedDir;

  Future<Uint8List?> posterFor(MediaItem item, {int maxDimension = 512}) async {
    final path = item.localPath;
    if (path == null || path.isEmpty) return null;

    // Best-effort stat for the cache key; a sandbox denial or missing file
    // just yields a coarser key (path + dimension only). Uses the async stat:
    // posterFor runs while grid tiles render, so synchronous filesystem I/O
    // here would block the UI isolate when many thumbnails are requested.
    int mtimeMs = 0;
    int sizeBytes = 0;
    try {
      final stat = await File(path).stat();
      mtimeMs = stat.modified.millisecondsSinceEpoch;
      sizeBytes = stat.size;
    } on FileSystemException {
      // Coarse key; native may still resolve via bookmark.
    }

    final key = cacheKeyFor(
      path: path,
      mtimeMs: mtimeMs,
      sizeBytes: sizeBytes,
      maxDimension: maxDimension,
    );

    final dir = _resolvedDir ??= await _cacheDir();
    // Format-agnostic extension: the cache stores whatever encoded bytes the
    // platform returned (JPEG from macOS QuickLook, PNG from the Windows shell
    // and ffmpegthumbnailer). Nothing decodes by filename - Image.memory sniffs
    // the container - so naming these .jpg would misdescribe most of them.
    final cacheFile = File(p.join(dir.path, '$key.img'));
    if (await cacheFile.exists()) {
      try {
        return await cacheFile.readAsBytes();
      } on FileSystemException {
        // Corrupt/unreadable cache entry: fall through and regenerate.
      }
    }

    Uint8List? blob;
    final ref = item.bookmarkRef;
    if (ref != null && ref.isNotEmpty) {
      blob = await _bookmarkStorage.read(ref);
    }

    final bytes = await _platform.generateVideoThumbnail(
      path: path,
      bookmarkBlob: blob,
      maxDimension: maxDimension,
    );
    if (bytes == null) return null;

    try {
      await dir.create(recursive: true);
      await cacheFile.writeAsBytes(bytes, flush: true);
    } on FileSystemException {
      // Caching is best-effort; still return the freshly generated bytes.
    }
    return bytes;
  }

  @visibleForTesting
  static String cacheKeyFor({
    required String path,
    required int mtimeMs,
    required int sizeBytes,
    required int maxDimension,
  }) {
    final basis = '$path|$mtimeMs|$sizeBytes|$maxDimension';
    return sha1.convert(utf8.encode(basis)).toString();
  }
}
