# Codecov configuration
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 80%

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "test/**"
  - "integration_test/**"
