import 'dart:developer' as developer;

import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:timezone/data/latest_all.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;

import 'package:submersion/core/util/tz_lookup_data.dart';
import 'package:submersion/core/util/wall_clock_utc.dart';

/// Offline mapping from a coordinate to its local clock.
///
/// Dive times are stored as wall-clock-as-UTC (see `wall_clock_utc.dart`),
/// but tide predictions need real instants. The zone for a coordinate comes
/// from a quadtree ported from photostructure/tz-lookup (data in
/// `tz_lookup_data.dart`, generated by
/// `scripts/tide/generate_tz_lookup_data.py`).
abstract final class SiteTimeZone {
  /// Replaces [zoneIdFor] inside the conversions, for tests only.
  @visibleForTesting
  static String Function(double latitude, double longitude)?
  debugZoneIdOverride;

  static final Set<String> _loggedMissingZones = {};
  static bool _fullDatabaseLoaded = false;

  /// The UTC instant at which the site's clocks show [wallClock]'s digits.
  ///
  /// Only the calendar and clock components of [wallClock] are read, so a
  /// wall-clock-as-UTC value and a local `DateTime` with the same digits
  /// give the same answer. The offset comes from tzdata for that date. In a
  /// spring-forward gap the time rolls forward by the gap (02:30 reads as
  /// 03:30 daylight time); in a fall-back overlap the earlier, daylight-time
  /// occurrence is used. Both behaviors are `package:timezone`'s.
  static DateTime instantFromWallClock(
    DateTime wallClock,
    double latitude,
    double longitude,
  ) {
    final local = tz.TZDateTime(
      _locationFor(latitude, longitude),
      wallClock.year,
      wallClock.month,
      wallClock.day,
      wallClock.hour,
      wallClock.minute,
      wallClock.second,
      wallClock.millisecond,
    );
    return DateTime.fromMillisecondsSinceEpoch(
      local.millisecondsSinceEpoch,
      isUtc: true,
    );
  }

  /// The site's wall-clock digits at [instant], as a wall-clock-as-UTC value
  /// (the flavor every tide formatter prints verbatim).
  static DateTime wallClockFromInstant(
    DateTime instant,
    double latitude,
    double longitude,
  ) => wallClockConverterFor(latitude, longitude)(instant);

  /// [wallClockFromInstant] with the site's zone resolved once, for mapping
  /// many instants at the same coordinate. The closure keeps only the
  /// resolved location.
  static DateTime Function(DateTime instant) wallClockConverterFor(
    double latitude,
    double longitude,
  ) {
    final location = _locationFor(latitude, longitude);
    return (instant) => asWallClockUtc(tz.TZDateTime.from(instant, location));
  }

  static tz.Location _locationFor(double latitude, double longitude) {
    final id = (debugZoneIdOverride ?? zoneIdFor)(latitude, longitude);
    return _find(id) ?? _find(etcZoneForLongitude(longitude)) ?? tz.UTC;
  }

  /// Looks [id] up. Another caller may have loaded a tzdata subset, so a
  /// miss loads the full database once. Loading resets `tz.local`, so the
  /// caller's local zone is restored afterwards.
  static tz.Location? _find(String id) {
    if (!tz.timeZoneDatabase.isInitialized) {
      tzdata.initializeTimeZones();
      _fullDatabaseLoaded = true;
    }
    final found = tz.timeZoneDatabase.locations[id];
    if (found != null) return found;
    if (!_fullDatabaseLoaded) {
      final previousLocal = tz.local.name;
      tzdata.initializeTimeZones();
      _fullDatabaseLoaded = true;
      final restored = tz.timeZoneDatabase.locations[previousLocal];
      if (restored != null) tz.setLocalLocation(restored);
      final retried = tz.timeZoneDatabase.locations[id];
      if (retried != null) return retried;
    }
    if (_loggedMissingZones.add(id)) {
      developer.log('Zone $id is missing from tzdata', name: 'SiteTimeZone');
    }
    return null;
  }

  /// IANA zone id for the coordinate. Never throws: open ocean yields an
  /// `Etc/GMT` zone from the data itself, and coordinates outside the valid
  /// range yield the `Etc/GMT` zone for their longitude.
  static String zoneIdFor(double latitude, double longitude) {
    final valid =
        latitude >= -90 &&
        latitude <= 90 &&
        longitude >= -180 &&
        longitude <= 180;
    if (!valid) return etcZoneForLongitude(longitude);
    if (latitude >= 90) return 'Etc/GMT';

    // Port of tzlookup() in tz.js. Variable names follow the original:
    // s/z track the column, u/d the row, k the node offset, v the level base.
    var v = -1;
    var s = 48 * (180 + longitude) / 360.00000000000006;
    var u = 24 * (90 - latitude) / 180.00000000000003;
    var z = s.toInt();
    var d = u.toInt();
    var k = 96 * d + 2 * z;
    k = 56 * tzLookupData.codeUnitAt(k) + tzLookupData.codeUnitAt(k + 1) - 1995;
    while (k + tzLookupZones.length < 3136) {
      v = v + k + 1;
      u = 2 * (u - d) % 2;
      d = u.toInt();
      s = 2 * (s - z) % 2;
      z = s.toInt();
      k = 8 * v + 4 * d + 2 * z + 2304;
      k =
          56 * tzLookupData.codeUnitAt(k) +
          tzLookupData.codeUnitAt(k + 1) -
          1995;
    }
    return tzLookupZones[k + tzLookupZones.length - 3136];
  }

  /// The fixed-offset `Etc/GMT` zone nearest to [longitude]. POSIX zone
  /// names invert the sign: 15 degrees east is `Etc/GMT-1`.
  static String etcZoneForLongitude(double longitude) {
    if (!longitude.isFinite) return 'Etc/GMT';
    final hours = (longitude.clamp(-180.0, 180.0) / 15).round().clamp(-12, 12);
    if (hours == 0) return 'Etc/GMT';
    return hours > 0 ? 'Etc/GMT-$hours' : 'Etc/GMT+${-hours}';
  }
}
