import 'package:submersion/core/util/tz_lookup_data.dart';

/// Offline mapping from a coordinate to its local clock.
///
/// Dive times are stored as wall-clock-as-UTC (see `wall_clock_utc.dart`),
/// but tide predictions need real instants. The zone for a coordinate comes
/// from a quadtree ported from photostructure/tz-lookup (data in
/// `tz_lookup_data.dart`, generated by
/// `scripts/tide/generate_tz_lookup_data.py`).
abstract final class SiteTimeZone {
  /// IANA zone id for the coordinate. Never throws: open ocean yields an
  /// `Etc/GMT` zone from the data itself, and coordinates outside the valid
  /// range yield the `Etc/GMT` zone for their longitude.
  static String zoneIdFor(double latitude, double longitude) {
    final valid =
        latitude >= -90 &&
        latitude <= 90 &&
        longitude >= -180 &&
        longitude <= 180;
    if (!valid) return etcZoneForLongitude(longitude);
    if (latitude >= 90) return 'Etc/GMT';

    // Port of tzlookup() in tz.js. Variable names follow the original:
    // s/z track the column, u/d the row, k the node offset, v the level base.
    var v = -1;
    var s = 48 * (180 + longitude) / 360.00000000000006;
    var u = 24 * (90 - latitude) / 180.00000000000003;
    var z = s.toInt();
    var d = u.toInt();
    var k = 96 * d + 2 * z;
    k = 56 * tzLookupData.codeUnitAt(k) + tzLookupData.codeUnitAt(k + 1) - 1995;
    while (k + tzLookupZones.length < 3136) {
      v = v + k + 1;
      u = 2 * (u - d) % 2;
      d = u.toInt();
      s = 2 * (s - z) % 2;
      z = s.toInt();
      k = 8 * v + 4 * d + 2 * z + 2304;
      k =
          56 * tzLookupData.codeUnitAt(k) +
          tzLookupData.codeUnitAt(k + 1) -
          1995;
    }
    return tzLookupZones[k + tzLookupZones.length - 3136];
  }

  /// The fixed-offset `Etc/GMT` zone nearest to [longitude]. POSIX zone
  /// names invert the sign: 15 degrees east is `Etc/GMT-1`.
  static String etcZoneForLongitude(double longitude) {
    if (!longitude.isFinite) return 'Etc/GMT';
    final hours = (longitude.clamp(-180.0, 180.0) / 15).round().clamp(-12, 12);
    if (hours == 0) return 'Etc/GMT';
    return hours > 0 ? 'Etc/GMT-$hours' : 'Etc/GMT+${-hours}';
  }
}
