import 'dart:developer' as developer;

import 'package:flutter/foundation.dart' show visibleForTesting;
import 'package:timezone/data/latest_all.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;

import 'package:submersion/core/util/tz_lookup_data.dart';

/// Offline mapping from a coordinate to its local clock.
///
/// Dive times are stored as wall-clock-as-UTC (see `wall_clock_utc.dart`),
/// but tide predictions need real instants. The zone for a coordinate comes
/// from a quadtree ported from photostructure/tz-lookup (data in
/// `tz_lookup_data.dart`, generated by
/// `scripts/tide/generate_tz_lookup_data.py`).
abstract final class SiteTimeZone {
  /// Replaces [zoneIdFor] inside the conversions, for tests only.
  @visibleForTesting
  static String Function(double latitude, double longitude)?
  debugZoneIdOverride;

  static final Set<String> _loggedMissingZones = {};

  /// The UTC instant at which the site's clocks show [wallClock]'s digits.
  ///
  /// Only the calendar and clock components of [wallClock] are read, so a
  /// wall-clock-as-UTC value and a local `DateTime` with the same digits
  /// give the same answer. The offset comes from tzdata for that date. In a
  /// spring-forward gap the time rolls forward by the gap (02:30 reads as
  /// 03:30 daylight time); in a fall-back overlap the earlier, daylight-time
  /// occurrence is used. Both behaviors are `package:timezone`'s.
  static DateTime instantFromWallClock(
    DateTime wallClock,
    double latitude,
    double longitude,
  ) {
    final local = tz.TZDateTime(
      _locationFor(latitude, longitude),
      wallClock.year,
      wallClock.month,
      wallClock.day,
      wallClock.hour,
      wallClock.minute,
      wallClock.second,
      wallClock.millisecond,
    );
    return DateTime.fromMillisecondsSinceEpoch(
      local.millisecondsSinceEpoch,
      isUtc: true,
    );
  }

  /// The site's wall-clock digits at [instant], as a wall-clock-as-UTC value
  /// (the flavor every tide formatter prints verbatim).
  static DateTime wallClockFromInstant(
    DateTime instant,
    double latitude,
    double longitude,
  ) {
    final local = tz.TZDateTime.from(
      instant,
      _locationFor(latitude, longitude),
    );
    return DateTime.utc(
      local.year,
      local.month,
      local.day,
      local.hour,
      local.minute,
      local.second,
      local.millisecond,
    );
  }

  static tz.Location _locationFor(double latitude, double longitude) {
    // Initializing resets tz.local, so never re-initialize a database the
    // notification service already loaded.
    if (!tz.timeZoneDatabase.isInitialized) tzdata.initializeTimeZones();
    final id = (debugZoneIdOverride ?? zoneIdFor)(latitude, longitude);
    try {
      return tz.getLocation(id);
    } on tz.LocationNotFoundException {
      if (_loggedMissingZones.add(id)) {
        developer.log(
          'Zone $id is missing from tzdata; using the longitude offset',
          name: 'SiteTimeZone',
        );
      }
      return tz.getLocation(etcZoneForLongitude(longitude));
    }
  }

  /// IANA zone id for the coordinate. Never throws: open ocean yields an
  /// `Etc/GMT` zone from the data itself, and coordinates outside the valid
  /// range yield the `Etc/GMT` zone for their longitude.
  static String zoneIdFor(double latitude, double longitude) {
    final valid =
        latitude >= -90 &&
        latitude <= 90 &&
        longitude >= -180 &&
        longitude <= 180;
    if (!valid) return etcZoneForLongitude(longitude);
    if (latitude >= 90) return 'Etc/GMT';

    // Port of tzlookup() in tz.js. Variable names follow the original:
    // s/z track the column, u/d the row, k the node offset, v the level base.
    var v = -1;
    var s = 48 * (180 + longitude) / 360.00000000000006;
    var u = 24 * (90 - latitude) / 180.00000000000003;
    var z = s.toInt();
    var d = u.toInt();
    var k = 96 * d + 2 * z;
    k = 56 * tzLookupData.codeUnitAt(k) + tzLookupData.codeUnitAt(k + 1) - 1995;
    while (k + tzLookupZones.length < 3136) {
      v = v + k + 1;
      u = 2 * (u - d) % 2;
      d = u.toInt();
      s = 2 * (s - z) % 2;
      z = s.toInt();
      k = 8 * v + 4 * d + 2 * z + 2304;
      k =
          56 * tzLookupData.codeUnitAt(k) +
          tzLookupData.codeUnitAt(k + 1) -
          1995;
    }
    return tzLookupZones[k + tzLookupZones.length - 3136];
  }

  /// The fixed-offset `Etc/GMT` zone nearest to [longitude]. POSIX zone
  /// names invert the sign: 15 degrees east is `Etc/GMT-1`.
  static String etcZoneForLongitude(double longitude) {
    if (!longitude.isFinite) return 'Etc/GMT';
    final hours = (longitude.clamp(-180.0, 180.0) / 15).round().clamp(-12, 12);
    if (hours == 0) return 'Etc/GMT';
    return hours > 0 ? 'Etc/GMT-$hours' : 'Etc/GMT+${-hours}';
  }
}
