import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';
import 'package:submersion/features/dive_lab/data/services/dive_lab_slate_pdf_service.dart';

const _labels = LabSlateLabels(
  title: 'Dive Lab slate',
  actual: 'Actual',
  whatIf: 'What if',
  delta: 'Delta',
  branch: 'Branch',
  mode: 'Mode',
  interventions: 'Interventions',
  gas: 'Gas',
  runtime: 'Runtime',
  issues: 'Issues',
  notes: 'Notes',
  depth: 'Depth',
  stop: 'Stop',
  runtimeColumn: 'Runtime',
  gasColumn: 'Gas',
  generated: 'Generated by Submersion',
);

/// A tiny PNG rendered through dart:ui, so the bytes are always valid.
Future<Uint8List> _png() async {
  final recorder = ui.PictureRecorder();
  final canvas = ui.Canvas(recorder);
  canvas.drawRect(
    const ui.Rect.fromLTWH(0, 0, 8, 8),
    ui.Paint()..color = const ui.Color(0xFF0077B6),
  );
  final image = await recorder.endRecording().toImage(8, 8);
  final data = await image.toByteData(format: ui.ImageByteFormat.png);
  return data!.buffer.asUint8List();
}

LabSlateScenario _scenario({Uint8List? png, bool replan = true}) =>
    LabSlateScenario(
      diveTitle: 'Dive #12, 2026-08-01',
      scenarioName: 'Lost 50%',
      branchText: '23:40 at 31.2 m',
      modeText: replan ? 'Re-plan' : 'Replay',
      interventionLabels: const ['Lost deco50', 'Ascend now'],
      deltaRows: const [
        ['Runtime', '58 min', '49 min', '-9:00'],
        ['Surface GF', '78%', '71%', '-7.0%'],
      ],
      gasRows: const [
        ['back', '200 bar → 62 bar', ''],
      ],
      runtimeRows: replan
          ? const [
              ['21 m', '1 min', '41:00', 'Air'],
              ['6 m', '8 min', '52:00', 'Air'],
            ]
          : null,
      issues: const [],
      notes: const ['SAC estimated'],
      settingsText: 'Settings: GF 30/70, Buhlmann ZH-L16C, real gas',
      chartPng: png,
    );

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test(
    'builds a PDF for one scenario, with and without a chart image',
    () async {
      const service = DiveLabSlatePdfService();
      final plain = await service.buildSlate(
        scenarios: [_scenario()],
        labels: _labels,
      );
      expect(String.fromCharCodes(plain.take(4)), '%PDF');
      expect(plain.length, greaterThan(1000));
      final withChart = await service.buildSlate(
        scenarios: [_scenario(png: await _png())],
        labels: _labels,
      );
      expect(String.fromCharCodes(withChart.take(4)), '%PDF');
    },
  );

  test('two scenarios produce a longer document than one', () async {
    const service = DiveLabSlatePdfService();
    final one = await service.buildSlate(
      scenarios: [_scenario()],
      labels: _labels,
    );
    final two = await service.buildSlate(
      scenarios: [_scenario(), _scenario(replan: false)],
      labels: _labels,
    );
    expect(two.length, greaterThan(one.length));
  });
}
