// GENERATED by tool/build_figure_artwork.py from tool/figure/. Do not edit.
// sources-digest: 90173dceb7f42fe152b610a94864eb7cd521f4c22fc3e598fff62971060653ee
// dart format off

import 'package:submersion/features/equipment/figure/domain/figure_piece_data.dart';
import 'package:submersion/features/equipment/figure/domain/figure_role.dart';
import 'package:submersion/features/equipment/figure/domain/figure_view.dart';

/// SHA-256 over the manifest and every SVG, so a test can tell when this
/// file is stale against its sources.
const String figureArtworkDigest = '90173dceb7f42fe152b610a94864eb7cd521f4c22fc3e598fff62971060653ee';

/// Every piece of artwork by id.
const Map<String, FigurePieceData> figureArtwork = {
  'body_front': FigurePieceData(
    id: 'body_front',
    view: FigureView.front,
    layer: 0,
    paths: [
      FigurePathData(role: FigureRole.body, d: 'M78 42A22 22 0 1 1 122 42A22 22 0 1 1 78 42Z'),
      FigurePathData(role: FigureRole.body, d: 'M92 60H108V74H92Z'),
      FigurePathData(role: FigureRole.body, d: 'M84 72H116A16 16 0 0 1 132 88V184A16 16 0 0 1 116 200H84A16 16 0 0 1 68 184V88A16 16 0 0 1 84 72Z'),
      FigurePathData(role: FigureRole.body, d: 'M70 82 L46 190 L60 194 L84 96 Z'),
      FigurePathData(role: FigureRole.body, d: 'M130 82 L154 190 L140 194 L116 96 Z'),
      FigurePathData(role: FigureRole.body, d: 'M29 214A11 11 0 1 1 51 214A11 11 0 1 1 29 214Z'),
      FigurePathData(role: FigureRole.body, d: 'M149 214A11 11 0 1 1 171 214A11 11 0 1 1 149 214Z'),
      FigurePathData(role: FigureRole.body, d: 'M78 196 L70 340 L94 340 L100 210 Z'),
      FigurePathData(role: FigureRole.body, d: 'M122 196 L130 340 L106 340 L100 210 Z'),
      FigurePathData(role: FigureRole.body, d: 'M73 338H89A5 5 0 0 1 94 343V353A5 5 0 0 1 89 358H73A5 5 0 0 1 68 353V343A5 5 0 0 1 73 338Z'),
      FigurePathData(role: FigureRole.body, d: 'M111 338H127A5 5 0 0 1 132 343V353A5 5 0 0 1 127 358H111A5 5 0 0 1 106 353V343A5 5 0 0 1 111 338Z'),
      FigurePathData(role: FigureRole.bodyShade, d: 'M126 80H126A6 6 0 0 1 132 86V186A6 6 0 0 1 126 192H126A6 6 0 0 1 120 186V86A6 6 0 0 1 126 80Z'),
      FigurePathData(role: FigureRole.bodyShade, d: 'M91 72A9 3 0 1 1 109 72A9 3 0 1 1 91 72Z'),
    ],
  ),
  'body_back': FigurePieceData(
    id: 'body_back',
    view: FigureView.back,
    layer: 0,
    paths: [
      FigurePathData(role: FigureRole.body, d: 'M78 42A22 22 0 1 1 122 42A22 22 0 1 1 78 42Z'),
      FigurePathData(role: FigureRole.body, d: 'M92 60H108V74H92Z'),
      FigurePathData(role: FigureRole.body, d: 'M84 72H116A16 16 0 0 1 132 88V184A16 16 0 0 1 116 200H84A16 16 0 0 1 68 184V88A16 16 0 0 1 84 72Z'),
      FigurePathData(role: FigureRole.body, d: 'M70 82 L46 190 L60 194 L84 96 Z'),
      FigurePathData(role: FigureRole.body, d: 'M130 82 L154 190 L140 194 L116 96 Z'),
      FigurePathData(role: FigureRole.body, d: 'M29 214A11 11 0 1 1 51 214A11 11 0 1 1 29 214Z'),
      FigurePathData(role: FigureRole.body, d: 'M149 214A11 11 0 1 1 171 214A11 11 0 1 1 149 214Z'),
      FigurePathData(role: FigureRole.body, d: 'M78 196 L70 340 L94 340 L100 210 Z'),
      FigurePathData(role: FigureRole.body, d: 'M122 196 L130 340 L106 340 L100 210 Z'),
      FigurePathData(role: FigureRole.body, d: 'M73 338H89A5 5 0 0 1 94 343V353A5 5 0 0 1 89 358H73A5 5 0 0 1 68 353V343A5 5 0 0 1 73 338Z'),
      FigurePathData(role: FigureRole.body, d: 'M111 338H127A5 5 0 0 1 132 343V353A5 5 0 0 1 127 358H111A5 5 0 0 1 106 353V343A5 5 0 0 1 111 338Z'),
      FigurePathData(role: FigureRole.bodyShade, d: 'M100 80H100A4 4 0 0 1 104 84V186A4 4 0 0 1 100 190H100A4 4 0 0 1 96 186V84A4 4 0 0 1 100 80Z'),
    ],
  ),
};
