// Pure helpers shared by the species catalog tools. Kept free of dart:io and
// the network so test/tool/species_tool_support_test.dart can cover them.
// (The directory is src, not lib, so that relative import passes the
// linter.)

/// App locales, in the order the ARB files are listed.
const List<String> appLocales = [
  'en',
  'de',
  'es',
  'fr',
  'it',
  'pt',
  'nl',
  'hu',
  'zh',
  'ar',
  'he',
];

final RegExp _idPattern = RegExp(r'^sp_[a-z0-9_]+$');

/// `sp_whale_shark` -> `whale_shark`, the part the ARB keys are built from.
String speciesSlug(String id) {
  if (!_idPattern.hasMatch(id)) {
    throw FormatException('Species id must match ${_idPattern.pattern}: $id');
  }
  return id.substring(3);
}

const String _generatedHeader =
    '// GENERATED by tool/generate_species_lookups.dart from\n'
    '// assets/data/species.json. Do not edit; rerun the tool.\n';

/// The full source of `species_name_lookup.dart` for [rows], which are the
/// `species` entries of the asset in their asset order.
String renderNameLookup(List<Map<String, dynamic>> rows) {
  final buffer = StringBuffer(_generatedHeader)
    ..write('''
import 'package:submersion/l10n/arb/app_localizations.dart';

/// Localized common names for the built-in species catalog.
///
/// The rows in `assets/data/species.json` are seeded into the `species`
/// table as English literals, and the stored `common_name` is what UDDF export
/// writes out, so that column deliberately stays English. Rendering it
/// directly is what left every species list in English under a translated
/// locale; on-screen callers resolve through here instead.
///
/// Keyed on the stable seed id rather than the name, matching
/// `builtInDiveTypeName`. Custom species carry a UUID id, so they can never
/// collide with an `sp_` slug and always fall through to null.
///
/// Returns null for anything that is not a known built-in id, and callers
/// fall back to the stored English name.
String? builtInSpeciesName(AppLocalizations l10n, String id) => switch (id) {
''');
  for (final row in rows) {
    final id = row['id'] as String;
    buffer.writeln("  '$id' => l10n.species_${speciesSlug(id)}_name,");
  }
  buffer.write('  _ => null,\n};\n');
  return buffer.toString();
}

/// The full source of `species_description_lookup.dart` for [rows].
String renderDescriptionLookup(List<Map<String, dynamic>> rows) {
  final buffer = StringBuffer(_generatedHeader)
    ..write('''
import 'package:submersion/l10n/arb/app_localizations.dart';

/// Localized descriptions for the built-in species catalog.
///
/// Companion to `builtInSpeciesName`; see that file for why the stored column
/// stays English. Split out purely to keep each generated file inside the
/// project's file-size budget.
///
/// Returns null for anything that is not a known built-in id, and callers
/// fall back to the stored English description.
String? builtInSpeciesDescription(
  AppLocalizations l10n,
  String id,
) => switch (id) {
''');
  for (final row in rows) {
    final id = row['id'] as String;
    buffer.writeln("  '$id' => l10n.species_${speciesSlug(id)}_desc,");
  }
  buffer.write('  _ => null,\n};\n');
  return buffer.toString();
}

class ArbSpeciesEntry {
  const ArbSpeciesEntry({
    required this.id,
    required this.name,
    required this.description,
  });

  final String id;
  final String name;
  final String description;
}

String _jsonString(String value) {
  final escaped = value
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n');
  return '"$escaped"';
}

/// Inserts `species_<slug>_name` and `_desc` lines after the last existing
/// `species_*_desc` line. The ARB files are feature blocks, not sorted, so
/// the anchor is positional. Throws if any key is already present.
String insertSpeciesArbKeys(String arbText, List<ArbSpeciesEntry> entries) {
  final lines = arbText.split('\n');
  final anchorPattern = RegExp(r'^  "species_[a-z0-9_]+_desc": ');
  var anchor = -1;
  for (var i = 0; i < lines.length; i++) {
    if (anchorPattern.hasMatch(lines[i])) anchor = i;
  }
  if (anchor == -1) {
    throw StateError('No species_*_desc key to anchor on');
  }
  final inserted = <String>[];
  for (final entry in entries) {
    final slug = speciesSlug(entry.id);
    for (final key in ['species_${slug}_name', 'species_${slug}_desc']) {
      if (arbText.contains('"$key"')) {
        throw StateError('$key already exists in the ARB file');
      }
    }
    inserted
      ..add('  "species_${slug}_name": ${_jsonString(entry.name)},')
      ..add('  "species_${slug}_desc": ${_jsonString(entry.description)},');
  }
  // The anchor line keeps its trailing comma; the inserted lines all carry
  // one, and the line after the anchor already existed, so the object stays
  // well-formed.
  lines.insertAll(anchor + 1, inserted);
  return lines.join('\n');
}

/// Which iNaturalist name locales serve each app locale, best first.
const Map<String, List<String>> _localeCandidates = {
  'en': ['en'],
  'de': ['de'],
  'es': ['es'],
  'fr': ['fr'],
  'it': ['it'],
  'pt': ['pt', 'pt-BR', 'pt-PT'],
  'nl': ['nl'],
  'hu': ['hu'],
  'zh': ['zh-CN', 'zh'],
  'ar': ['ar'],
  'he': ['he'],
};

/// One name per app locale from a `/v1/taxa?...&all_names=true` taxon: the
/// valid name with the lowest `position` for the best candidate locale,
/// falling back to the taxon's English name, then to [englishFallback].
Map<String, String> localizedNamesFromTaxon(
  Map<String, dynamic> taxon, {
  required String englishFallback,
}) {
  final names = (taxon['names'] as List? ?? const [])
      .cast<Map<String, dynamic>>()
      .where((n) => n['is_valid'] != false && n['name'] is String)
      .toList();

  String? best(List<String> candidates) {
    for (final locale in candidates) {
      final matches = names.where((n) => n['locale'] == locale).toList()
        ..sort(
          (a, b) => ((a['position'] as int?) ?? 1 << 30).compareTo(
            (b['position'] as int?) ?? 1 << 30,
          ),
        );
      if (matches.isNotEmpty) return matches.first['name'] as String;
    }
    return null;
  }

  final english =
      best(['en']) ??
      taxon['preferred_common_name'] as String? ??
      englishFallback;
  return {
    for (final locale in appLocales)
      locale: locale == 'en'
          ? english
          : best(_localeCandidates[locale]!) ?? english,
  };
}

/// The seed's curated English name replaces the taxon's English name
/// everywhere it was used: iNaturalist prefers regional or split-taxon
/// names ("Florida Bass", "Amur Carp") that divers do not use, and every
/// locale that fell back to English should fall back to the curated one.
/// [overrides] (locale -> name, hand-authored) then wins over both.
Map<String, String> applyCuratedNames(
  Map<String, String> names,
  String curatedEnglish, {
  Map<String, dynamic> overrides = const {},
}) {
  final taxonEnglish = names['en'];
  return {
    for (final entry in names.entries)
      entry.key: overrides[entry.key] is String
          ? overrides[entry.key] as String
          : (entry.key == 'en' || entry.value == taxonEnglish)
          ? curatedEnglish
          : entry.value,
  };
}
