// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.submersion.libdivecomputer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class TransportType(val raw: Int) {
  BLE(0),
  USB(1),
  SERIAL(2),
  INFRARED(3);

  companion object {
    fun ofRaw(raw: Int): TransportType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DeviceDescriptor (
  val vendor: String,
  val product: String,
  val model: Long,
  val transports: List<TransportType>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceDescriptor {
      val vendor = pigeonVar_list[0] as String
      val product = pigeonVar_list[1] as String
      val model = pigeonVar_list[2] as Long
      val transports = pigeonVar_list[3] as List<TransportType>
      return DeviceDescriptor(vendor, product, model, transports)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vendor,
      product,
      model,
      transports,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiscoveredDevice (
  val vendor: String,
  val product: String,
  val model: Long,
  val address: String,
  val name: String? = null,
  val transport: TransportType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiscoveredDevice {
      val vendor = pigeonVar_list[0] as String
      val product = pigeonVar_list[1] as String
      val model = pigeonVar_list[2] as Long
      val address = pigeonVar_list[3] as String
      val name = pigeonVar_list[4] as String?
      val transport = pigeonVar_list[5] as TransportType
      return DiscoveredDevice(vendor, product, model, address, name, transport)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vendor,
      product,
      model,
      address,
      name,
      transport,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProfileSample (
  val timeSeconds: Long,
  val depthMeters: Double,
  val temperatureCelsius: Double? = null,
  val pressureBar: Double? = null,
  val tankIndex: Long? = null,
  val heartRate: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileSample {
      val timeSeconds = pigeonVar_list[0] as Long
      val depthMeters = pigeonVar_list[1] as Double
      val temperatureCelsius = pigeonVar_list[2] as Double?
      val pressureBar = pigeonVar_list[3] as Double?
      val tankIndex = pigeonVar_list[4] as Long?
      val heartRate = pigeonVar_list[5] as Double?
      return ProfileSample(timeSeconds, depthMeters, temperatureCelsius, pressureBar, tankIndex, heartRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeSeconds,
      depthMeters,
      temperatureCelsius,
      pressureBar,
      tankIndex,
      heartRate,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GasMix (
  val index: Long,
  val o2Percent: Double,
  val hePercent: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GasMix {
      val index = pigeonVar_list[0] as Long
      val o2Percent = pigeonVar_list[1] as Double
      val hePercent = pigeonVar_list[2] as Double
      return GasMix(index, o2Percent, hePercent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      o2Percent,
      hePercent,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TankInfo (
  val index: Long,
  val gasMixIndex: Long,
  val volumeLiters: Double? = null,
  val startPressureBar: Double? = null,
  val endPressureBar: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TankInfo {
      val index = pigeonVar_list[0] as Long
      val gasMixIndex = pigeonVar_list[1] as Long
      val volumeLiters = pigeonVar_list[2] as Double?
      val startPressureBar = pigeonVar_list[3] as Double?
      val endPressureBar = pigeonVar_list[4] as Double?
      return TankInfo(index, gasMixIndex, volumeLiters, startPressureBar, endPressureBar)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      gasMixIndex,
      volumeLiters,
      startPressureBar,
      endPressureBar,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiveEvent (
  val timeSeconds: Long,
  val type: String,
  val data: Map<String, String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiveEvent {
      val timeSeconds = pigeonVar_list[0] as Long
      val type = pigeonVar_list[1] as String
      val data = pigeonVar_list[2] as Map<String, String>?
      return DiveEvent(timeSeconds, type, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timeSeconds,
      type,
      data,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ParsedDive (
  val fingerprint: String,
  val dateTimeEpoch: Long,
  val maxDepthMeters: Double,
  val avgDepthMeters: Double,
  val durationSeconds: Long,
  val minTemperatureCelsius: Double? = null,
  val maxTemperatureCelsius: Double? = null,
  val samples: List<ProfileSample>,
  val tanks: List<TankInfo>,
  val gasMixes: List<GasMix>,
  val events: List<DiveEvent>,
  val diveMode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ParsedDive {
      val fingerprint = pigeonVar_list[0] as String
      val dateTimeEpoch = pigeonVar_list[1] as Long
      val maxDepthMeters = pigeonVar_list[2] as Double
      val avgDepthMeters = pigeonVar_list[3] as Double
      val durationSeconds = pigeonVar_list[4] as Long
      val minTemperatureCelsius = pigeonVar_list[5] as Double?
      val maxTemperatureCelsius = pigeonVar_list[6] as Double?
      val samples = pigeonVar_list[7] as List<ProfileSample>
      val tanks = pigeonVar_list[8] as List<TankInfo>
      val gasMixes = pigeonVar_list[9] as List<GasMix>
      val events = pigeonVar_list[10] as List<DiveEvent>
      val diveMode = pigeonVar_list[11] as String?
      return ParsedDive(fingerprint, dateTimeEpoch, maxDepthMeters, avgDepthMeters, durationSeconds, minTemperatureCelsius, maxTemperatureCelsius, samples, tanks, gasMixes, events, diveMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fingerprint,
      dateTimeEpoch,
      maxDepthMeters,
      avgDepthMeters,
      durationSeconds,
      minTemperatureCelsius,
      maxTemperatureCelsius,
      samples,
      tanks,
      gasMixes,
      events,
      diveMode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadProgress (
  val current: Long,
  val total: Long,
  val status: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadProgress {
      val current = pigeonVar_list[0] as Long
      val total = pigeonVar_list[1] as Long
      val status = pigeonVar_list[2] as String
      return DownloadProgress(current, total, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      current,
      total,
      status,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DiveComputerError (
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DiveComputerError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return DiveComputerError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
}
private open class DiveComputerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TransportType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceDescriptor.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiscoveredDevice.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileSample.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GasMix.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TankInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiveEvent.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ParsedDive.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadProgress.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DiveComputerError.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TransportType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is DeviceDescriptor -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DiscoveredDevice -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ProfileSample -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is GasMix -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TankInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is DiveEvent -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ParsedDive -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is DownloadProgress -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is DiveComputerError -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DiveComputerHostApi {
  fun getDeviceDescriptors(callback: (Result<List<DeviceDescriptor>>) -> Unit)
  fun startDiscovery(transport: TransportType, callback: (Result<Unit>) -> Unit)
  fun stopDiscovery()
  fun startDownload(device: DiscoveredDevice, callback: (Result<Unit>) -> Unit)
  fun cancelDownload()
  fun getLibdivecomputerVersion(): String

  companion object {
    /** The codec used by DiveComputerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DiveComputerApiPigeonCodec()
    }
    /** Sets up an instance of `DiveComputerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DiveComputerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getDeviceDescriptors$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceDescriptors{ result: Result<List<DeviceDescriptor>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val transportArg = args[0] as TransportType
            api.startDiscovery(transportArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as DiscoveredDevice
            api.startDownload(deviceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelDownload()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getLibdivecomputerVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLibdivecomputerVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DiveComputerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DiveComputerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DiveComputerApiPigeonCodec()
    }
  }
  fun onDeviceDiscovered(deviceArg: DiscoveredDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDeviceDiscovered$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDiscoveryComplete(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiscoveryComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadProgress(progressArg: DownloadProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDiveDownloaded(diveArg: ParsedDive, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiveDownloaded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(diveArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDownloadComplete(totalDivesArg: Long, serialNumberArg: String?, firmwareVersionArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(totalDivesArg, serialNumberArg, firmwareVersionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onError(errorArg: DiveComputerError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
