// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/dive_computer/presentation/providers/download_notifier_fingerprint_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:libdivecomputer_plugin/src/dive_computer_service.dart' as _i9;
import 'package:libdivecomputer_plugin/src/generated/dive_computer_api.g.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:submersion/core/database/database.dart' as _i6;
import 'package:submersion/features/dive_computer/data/services/dive_import_service.dart'
    as _i4;
import 'package:submersion/features/dive_computer/domain/entities/downloaded_dive.dart'
    as _i8;
import 'package:submersion/features/dive_log/data/repositories/dive_computer_repository_impl.dart'
    as _i3;
import 'package:submersion/features/dive_log/domain/entities/dive_computer.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiveComputer_0 extends _i1.SmartFake implements _i2.DiveComputer {
  _FakeDiveComputer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveComputerStats_1 extends _i1.SmartFake
    implements _i3.DiveComputerStats {
  _FakeDiveComputerStats_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImportResult_2 extends _i1.SmartFake implements _i4.ImportResult {
  _FakeImportResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuplicateResult_3 extends _i1.SmartFake
    implements _i4.DuplicateResult {
  _FakeDuplicateResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiveComputerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveComputerRepository extends _i1.Mock
    implements _i3.DiveComputerRepository {
  MockDiveComputerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.DiveComputer>> getAllComputers({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllComputers, [], {#diverId: diverId}),
            returnValue: _i5.Future<List<_i2.DiveComputer>>.value(
              <_i2.DiveComputer>[],
            ),
          )
          as _i5.Future<List<_i2.DiveComputer>>);

  @override
  _i5.Future<_i2.DiveComputer?> getComputerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerById, [id]),
            returnValue: _i5.Future<_i2.DiveComputer?>.value(),
          )
          as _i5.Future<_i2.DiveComputer?>);

  @override
  _i5.Future<_i2.DiveComputer?> getFavoriteComputer({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteComputer, [], {#diverId: diverId}),
            returnValue: _i5.Future<_i2.DiveComputer?>.value(),
          )
          as _i5.Future<_i2.DiveComputer?>);

  @override
  _i5.Future<_i2.DiveComputer?> findByBluetoothAddress(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#findByBluetoothAddress, [address]),
            returnValue: _i5.Future<_i2.DiveComputer?>.value(),
          )
          as _i5.Future<_i2.DiveComputer?>);

  @override
  _i5.Future<_i2.DiveComputer> createComputer(_i2.DiveComputer? computer) =>
      (super.noSuchMethod(
            Invocation.method(#createComputer, [computer]),
            returnValue: _i5.Future<_i2.DiveComputer>.value(
              _FakeDiveComputer_0(
                this,
                Invocation.method(#createComputer, [computer]),
              ),
            ),
          )
          as _i5.Future<_i2.DiveComputer>);

  @override
  _i5.Future<void> updateComputer(_i2.DiveComputer? computer) =>
      (super.noSuchMethod(
            Invocation.method(#updateComputer, [computer]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteComputer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComputer, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setFavoriteComputer(String? id, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#setFavoriteComputer, [id], {#diverId: diverId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> incrementDiveCount(String? id, {int? by = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#incrementDiveCount, [id], {#by: by}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLastDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastDownload, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLastFingerprint(String? id, String? fingerprint) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastFingerprint, [id, fingerprint]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.DiveProfile>> getProfilesForDive(
    String? diveId, {
    String? computerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProfilesForDive,
              [diveId],
              {#computerId: computerId},
            ),
            returnValue: _i5.Future<List<_i6.DiveProfile>>.value(
              <_i6.DiveProfile>[],
            ),
          )
          as _i5.Future<List<_i6.DiveProfile>>);

  @override
  _i5.Future<List<String>> getComputerIdsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerIdsForDive, [diveId]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i2.DiveComputer>> getComputersForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getComputersForDive, [diveId]),
            returnValue: _i5.Future<List<_i2.DiveComputer>>.value(
              <_i2.DiveComputer>[],
            ),
          )
          as _i5.Future<List<_i2.DiveComputer>>);

  @override
  _i5.Future<String?> getPrimaryComputerId(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrimaryComputerId, [diveId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setPrimaryProfile(String? diveId, String? computerId) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryProfile, [diveId, computerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> findMatchingDive({
    required DateTime? profileStartTime,
    int? toleranceMinutes = 5,
    int? durationSeconds,
    double? maxDepth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchingDive, [], {
              #profileStartTime: profileStartTime,
              #toleranceMinutes: toleranceMinutes,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i3.DiveMatchResult?> findMatchingDiveWithScore({
    required DateTime? profileStartTime,
    int? toleranceMinutes = 5,
    int? durationSeconds,
    double? maxDepth,
    String? fingerprint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchingDiveWithScore, [], {
              #profileStartTime: profileStartTime,
              #toleranceMinutes: toleranceMinutes,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
              #fingerprint: fingerprint,
            }),
            returnValue: _i5.Future<_i3.DiveMatchResult?>.value(),
          )
          as _i5.Future<_i3.DiveMatchResult?>);

  @override
  _i5.Future<_i3.DiveComputerStats> getComputerStats(String? computerId) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerStats, [computerId]),
            returnValue: _i5.Future<_i3.DiveComputerStats>.value(
              _FakeDiveComputerStats_1(
                this,
                Invocation.method(#getComputerStats, [computerId]),
              ),
            ),
          )
          as _i5.Future<_i3.DiveComputerStats>);

  @override
  _i5.Future<List<String>> getDiveIdsForComputer(
    String? computerId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveIdsForComputer,
              [computerId],
              {#limit: limit},
            ),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<String> importProfile({
    required String? computerId,
    required DateTime? profileStartTime,
    required List<_i3.ProfilePointData>? points,
    required int? durationSeconds,
    double? maxDepth,
    double? avgDepth,
    bool? isPrimary = false,
    String? diverId,
    List<_i3.TankData>? tanks,
    String? decoAlgorithm,
    int? gfLow,
    int? gfHigh,
    int? decoConservatism,
    List<_i3.EventData>? events,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importProfile, [], {
              #computerId: computerId,
              #profileStartTime: profileStartTime,
              #points: points,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
              #avgDepth: avgDepth,
              #isPrimary: isPrimary,
              #diverId: diverId,
              #tanks: tanks,
              #decoAlgorithm: decoAlgorithm,
              #gfLow: gfLow,
              #gfHigh: gfHigh,
              #decoConservatism: decoConservatism,
              #events: events,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#importProfile, [], {
                  #computerId: computerId,
                  #profileStartTime: profileStartTime,
                  #points: points,
                  #durationSeconds: durationSeconds,
                  #maxDepth: maxDepth,
                  #avgDepth: avgDepth,
                  #isPrimary: isPrimary,
                  #diverId: diverId,
                  #tanks: tanks,
                  #decoAlgorithm: decoAlgorithm,
                  #gfLow: gfLow,
                  #gfHigh: gfHigh,
                  #decoConservatism: decoConservatism,
                  #events: events,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i2.DiveComputer> findOrCreateComputer({
    required String? serialNumber,
    String? diverId,
    String? manufacturer,
    String? model,
    String? connectionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreateComputer, [], {
              #serialNumber: serialNumber,
              #diverId: diverId,
              #manufacturer: manufacturer,
              #model: model,
              #connectionType: connectionType,
            }),
            returnValue: _i5.Future<_i2.DiveComputer>.value(
              _FakeDiveComputer_0(
                this,
                Invocation.method(#findOrCreateComputer, [], {
                  #serialNumber: serialNumber,
                  #diverId: diverId,
                  #manufacturer: manufacturer,
                  #model: model,
                  #connectionType: connectionType,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.DiveComputer>);

  @override
  _i5.Future<List<_i6.DiveProfileEvent>> getEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsForDive, [diveId]),
            returnValue: _i5.Future<List<_i6.DiveProfileEvent>>.value(
              <_i6.DiveProfileEvent>[],
            ),
          )
          as _i5.Future<List<_i6.DiveProfileEvent>>);

  @override
  _i5.Future<void> addProfileEvent({
    required String? diveId,
    required int? timestamp,
    required String? eventType,
    String? severity = 'info',
    String? description,
    double? depth,
    double? value,
    String? tankId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProfileEvent, [], {
              #diveId: diveId,
              #timestamp: timestamp,
              #eventType: eventType,
              #severity: severity,
              #description: description,
              #depth: depth,
              #value: value,
              #tankId: tankId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#clearEventsForDive, [diveId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [DiveImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveImportService extends _i1.Mock implements _i4.DiveImportService {
  MockDiveImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.ImportResult> importDives({
    required List<_i8.DownloadedDive>? dives,
    required _i2.DiveComputer? computer,
    _i4.ImportMode? mode = _i4.ImportMode.newOnly,
    _i4.ConflictResolution? defaultResolution = _i4.ConflictResolution.skip,
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importDives, [], {
              #dives: dives,
              #computer: computer,
              #mode: mode,
              #defaultResolution: defaultResolution,
              #diverId: diverId,
            }),
            returnValue: _i5.Future<_i4.ImportResult>.value(
              _FakeImportResult_2(
                this,
                Invocation.method(#importDives, [], {
                  #dives: dives,
                  #computer: computer,
                  #mode: mode,
                  #defaultResolution: defaultResolution,
                  #diverId: diverId,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.ImportResult>);

  @override
  _i5.Future<_i4.DuplicateResult> detectDuplicate(
    _i8.DownloadedDive? dive, {
    double? timeTolerance = 5.0,
    double? depthTolerance = 0.5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #detectDuplicate,
              [dive],
              {#timeTolerance: timeTolerance, #depthTolerance: depthTolerance},
            ),
            returnValue: _i5.Future<_i4.DuplicateResult>.value(
              _FakeDuplicateResult_3(
                this,
                Invocation.method(
                  #detectDuplicate,
                  [dive],
                  {
                    #timeTolerance: timeTolerance,
                    #depthTolerance: depthTolerance,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i4.DuplicateResult>);

  @override
  _i5.Future<String?> resolveConflict(
    _i4.ImportConflict? conflict,
    _i4.ConflictResolution? resolution,
    String? computerId, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveConflict,
              [conflict, resolution, computerId],
              {#diverId: diverId},
            ),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [DiveComputerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveComputerService extends _i1.Mock
    implements _i9.DiveComputerService {
  MockDiveComputerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i10.DiscoveredDevice> get discoveredDevices =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredDevices),
            returnValue: _i5.Stream<_i10.DiscoveredDevice>.empty(),
          )
          as _i5.Stream<_i10.DiscoveredDevice>);

  @override
  _i5.Stream<void> get discoveryComplete =>
      (super.noSuchMethod(
            Invocation.getter(#discoveryComplete),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i5.Stream<_i9.DownloadEvent> get downloadEvents =>
      (super.noSuchMethod(
            Invocation.getter(#downloadEvents),
            returnValue: _i5.Stream<_i9.DownloadEvent>.empty(),
          )
          as _i5.Stream<_i9.DownloadEvent>);

  @override
  _i5.Future<List<_i10.DeviceDescriptor>> getDeviceDescriptors() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceDescriptors, []),
            returnValue: _i5.Future<List<_i10.DeviceDescriptor>>.value(
              <_i10.DeviceDescriptor>[],
            ),
          )
          as _i5.Future<List<_i10.DeviceDescriptor>>);

  @override
  _i5.Future<String> getVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getVersion, []),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#getVersion, [])),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> startDiscovery(_i10.TransportType? transport) =>
      (super.noSuchMethod(
            Invocation.method(#startDiscovery, [transport]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startDownload(
    _i10.DiscoveredDevice? device, {
    String? fingerprint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startDownload,
              [device],
              {#fingerprint: fingerprint},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelDownload() =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> submitPinCode(String? pinCode) =>
      (super.noSuchMethod(
            Invocation.method(#submitPinCode, [pinCode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onDeviceDiscovered(_i10.DiscoveredDevice? device) => super.noSuchMethod(
    Invocation.method(#onDeviceDiscovered, [device]),
    returnValueForMissingStub: null,
  );

  @override
  void onDiscoveryComplete() => super.noSuchMethod(
    Invocation.method(#onDiscoveryComplete, []),
    returnValueForMissingStub: null,
  );

  @override
  void onDownloadProgress(_i10.DownloadProgress? progress) =>
      super.noSuchMethod(
        Invocation.method(#onDownloadProgress, [progress]),
        returnValueForMissingStub: null,
      );

  @override
  void onDiveDownloaded(_i10.ParsedDive? dive) => super.noSuchMethod(
    Invocation.method(#onDiveDownloaded, [dive]),
    returnValueForMissingStub: null,
  );

  @override
  void onDownloadComplete(
    int? totalDives,
    String? serialNumber,
    String? firmwareVersion,
  ) => super.noSuchMethod(
    Invocation.method(#onDownloadComplete, [
      totalDives,
      serialNumber,
      firmwareVersion,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(_i10.DiveComputerError? error) => super.noSuchMethod(
    Invocation.method(#onError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void onPinCodeRequired(String? deviceAddress) => super.noSuchMethod(
    Invocation.method(#onPinCodeRequired, [deviceAddress]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
