// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/tags/presentation/widgets/tag_merge_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:submersion/features/tags/data/repositories/tag_repository.dart'
    as _i3;
import 'package:submersion/features/tags/domain/entities/tag.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTag_0 extends _i1.SmartFake implements _i2.Tag {
  _FakeTag_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TagRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagRepository extends _i1.Mock implements _i3.TagRepository {
  MockTagRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Tag>> getAllTags({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, [], {#diverId: diverId}),
            returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
          )
          as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<_i2.Tag?> getTagById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTagById, [id]),
            returnValue: _i4.Future<_i2.Tag?>.value(),
          )
          as _i4.Future<_i2.Tag?>);

  @override
  _i4.Future<_i2.Tag?> getTagByName(String? name, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getTagByName, [name], {#diverId: diverId}),
            returnValue: _i4.Future<_i2.Tag?>.value(),
          )
          as _i4.Future<_i2.Tag?>);

  @override
  _i4.Future<_i2.Tag> createTag(_i2.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#createTag, [tag]),
            returnValue: _i4.Future<_i2.Tag>.value(
              _FakeTag_0(this, Invocation.method(#createTag, [tag])),
            ),
          )
          as _i4.Future<_i2.Tag>);

  @override
  _i4.Future<_i2.Tag> getOrCreateTag(
    String? name, {
    String? colorHex,
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getOrCreateTag,
              [name],
              {#colorHex: colorHex, #diverId: diverId},
            ),
            returnValue: _i4.Future<_i2.Tag>.value(
              _FakeTag_0(
                this,
                Invocation.method(
                  #getOrCreateTag,
                  [name],
                  {#colorHex: colorHex, #diverId: diverId},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Tag>);

  @override
  _i4.Future<void> updateTag(_i2.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#updateTag, [tag]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTag(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Tag>> getTagsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagsForDive, [diveId]),
            returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
          )
          as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<Map<String, List<_i2.Tag>>> getTagsForDives(
    List<String>? diveIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTagsForDives, [diveIds]),
            returnValue: _i4.Future<Map<String, List<_i2.Tag>>>.value(
              <String, List<_i2.Tag>>{},
            ),
          )
          as _i4.Future<Map<String, List<_i2.Tag>>>);

  @override
  _i4.Future<void> setTagsForDive(String? diveId, List<_i2.Tag>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#setTagsForDive, [diveId, tags]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addTagToDive(String? diveId, String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#addTagToDive, [diveId, tagId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeTagFromDive(String? diveId, String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromDive, [diveId, tagId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.TagStatistic>> getTagStatistics({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getTagStatistics, [], {#diverId: diverId}),
            returnValue: _i4.Future<List<_i3.TagStatistic>>.value(
              <_i3.TagStatistic>[],
            ),
          )
          as _i4.Future<List<_i3.TagStatistic>>);

  @override
  _i4.Future<int> getTagUsageCount(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagUsageCount, [tagId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getMergedDiveCount(List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#getMergedDiveCount, [tagIds]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.Tag>> searchTags(String? query, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchTags, [query], {#diverId: diverId}),
            returnValue: _i4.Future<List<_i2.Tag>>.value(<_i2.Tag>[]),
          )
          as _i4.Future<List<_i2.Tag>>);

  @override
  _i4.Future<void> mergeTags({
    required List<String>? sourceTagIds,
    required String? survivingTagId,
    required String? name,
    required String? colorHex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeTags, [], {
              #sourceTagIds: sourceTagIds,
              #survivingTagId: survivingTagId,
              #name: name,
              #colorHex: colorHex,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
