// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/import_wizard/data/adapters/dive_computer_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:submersion/core/constants/sort_options.dart' as _i15;
import 'package:submersion/core/database/database.dart' as _i11;
import 'package:submersion/core/models/sort_state.dart' as _i14;
import 'package:submersion/features/dive_computer/data/services/dive_import_service.dart'
    as _i2;
import 'package:submersion/features/dive_computer/domain/entities/downloaded_dive.dart'
    as _i8;
import 'package:submersion/features/dive_log/data/repositories/dive_computer_repository_impl.dart'
    as _i10;
import 'package:submersion/features/dive_log/data/repositories/dive_repository_impl.dart'
    as _i5;
import 'package:submersion/features/dive_log/domain/entities/dive.dart' as _i4;
import 'package:submersion/features/dive_log/domain/entities/dive_computer.dart'
    as _i3;
import 'package:submersion/features/dive_log/domain/entities/dive_data_source.dart'
    as _i16;
import 'package:submersion/features/dive_log/domain/entities/dive_summary.dart'
    as _i12;
import 'package:submersion/features/dive_log/domain/entities/gas_switch.dart'
    as _i6;
import 'package:submersion/features/dive_log/domain/models/dive_filter_state.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImportResult_0 extends _i1.SmartFake implements _i2.ImportResult {
  _FakeImportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuplicateResult_1 extends _i1.SmartFake
    implements _i2.DuplicateResult {
  _FakeDuplicateResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveComputer_2 extends _i1.SmartFake implements _i3.DiveComputer {
  _FakeDiveComputer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDive_3 extends _i1.SmartFake implements _i4.Dive {
  _FakeDive_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveStatistics_4 extends _i1.SmartFake
    implements _i5.DiveStatistics {
  _FakeDiveStatistics_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveRecords_5 extends _i1.SmartFake implements _i5.DiveRecords {
  _FakeDiveRecords_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGasSwitch_6 extends _i1.SmartFake implements _i6.GasSwitch {
  _FakeGasSwitch_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveNumberingInfo_7 extends _i1.SmartFake
    implements _i5.DiveNumberingInfo {
  _FakeDiveNumberingInfo_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiveImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveImportService extends _i1.Mock implements _i2.DiveImportService {
  @override
  _i7.Future<_i2.ImportResult> importDives({
    required List<_i8.DownloadedDive>? dives,
    required _i3.DiveComputer? computer,
    _i2.ImportMode? mode = _i2.ImportMode.newOnly,
    _i2.ConflictResolution? defaultResolution = _i2.ConflictResolution.skip,
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importDives, [], {
              #dives: dives,
              #computer: computer,
              #mode: mode,
              #defaultResolution: defaultResolution,
              #diverId: diverId,
            }),
            returnValue: _i7.Future<_i2.ImportResult>.value(
              _FakeImportResult_0(
                this,
                Invocation.method(#importDives, [], {
                  #dives: dives,
                  #computer: computer,
                  #mode: mode,
                  #defaultResolution: defaultResolution,
                  #diverId: diverId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.ImportResult>.value(
              _FakeImportResult_0(
                this,
                Invocation.method(#importDives, [], {
                  #dives: dives,
                  #computer: computer,
                  #mode: mode,
                  #defaultResolution: defaultResolution,
                  #diverId: diverId,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.ImportResult>);

  @override
  _i7.Future<_i2.DuplicateResult> detectDuplicate(
    _i8.DownloadedDive? dive, {
    double? timeTolerance = 5.0,
    double? depthTolerance = 0.5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #detectDuplicate,
              [dive],
              {#timeTolerance: timeTolerance, #depthTolerance: depthTolerance},
            ),
            returnValue: _i7.Future<_i2.DuplicateResult>.value(
              _FakeDuplicateResult_1(
                this,
                Invocation.method(
                  #detectDuplicate,
                  [dive],
                  {
                    #timeTolerance: timeTolerance,
                    #depthTolerance: depthTolerance,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.DuplicateResult>.value(
              _FakeDuplicateResult_1(
                this,
                Invocation.method(
                  #detectDuplicate,
                  [dive],
                  {
                    #timeTolerance: timeTolerance,
                    #depthTolerance: depthTolerance,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.DuplicateResult>);

  @override
  _i7.Future<String> importSingleDiveAsNew(
    _i8.DownloadedDive? dive, {
    required String? computerId,
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importSingleDiveAsNew,
              [dive],
              {#computerId: computerId, #diverId: diverId},
            ),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(
                  #importSingleDiveAsNew,
                  [dive],
                  {#computerId: computerId, #diverId: diverId},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(
                  #importSingleDiveAsNew,
                  [dive],
                  {#computerId: computerId, #diverId: diverId},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String?> resolveConflict(
    _i2.ImportConflict? conflict,
    _i2.ConflictResolution? resolution,
    String? computerId, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveConflict,
              [conflict, resolution, computerId],
              {#diverId: diverId},
            ),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);
}

/// A class which mocks [DiveComputerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveComputerRepository extends _i1.Mock
    implements _i10.DiveComputerRepository {
  @override
  _i7.Future<List<_i3.DiveComputer>> getAllComputers({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllComputers, [], {#diverId: diverId}),
            returnValue: _i7.Future<List<_i3.DiveComputer>>.value(
              <_i3.DiveComputer>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i3.DiveComputer>>.value(
              <_i3.DiveComputer>[],
            ),
          )
          as _i7.Future<List<_i3.DiveComputer>>);

  @override
  _i7.Future<_i3.DiveComputer?> getComputerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerById, [id]),
            returnValue: _i7.Future<_i3.DiveComputer?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.DiveComputer?>.value(),
          )
          as _i7.Future<_i3.DiveComputer?>);

  @override
  _i7.Future<_i3.DiveComputer?> getFavoriteComputer({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteComputer, [], {#diverId: diverId}),
            returnValue: _i7.Future<_i3.DiveComputer?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.DiveComputer?>.value(),
          )
          as _i7.Future<_i3.DiveComputer?>);

  @override
  _i7.Future<_i3.DiveComputer?> findByBluetoothAddress(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#findByBluetoothAddress, [address]),
            returnValue: _i7.Future<_i3.DiveComputer?>.value(),
            returnValueForMissingStub: _i7.Future<_i3.DiveComputer?>.value(),
          )
          as _i7.Future<_i3.DiveComputer?>);

  @override
  _i7.Future<_i3.DiveComputer> createComputer(_i3.DiveComputer? computer) =>
      (super.noSuchMethod(
            Invocation.method(#createComputer, [computer]),
            returnValue: _i7.Future<_i3.DiveComputer>.value(
              _FakeDiveComputer_2(
                this,
                Invocation.method(#createComputer, [computer]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.DiveComputer>.value(
              _FakeDiveComputer_2(
                this,
                Invocation.method(#createComputer, [computer]),
              ),
            ),
          )
          as _i7.Future<_i3.DiveComputer>);

  @override
  _i7.Future<void> updateComputer(_i3.DiveComputer? computer) =>
      (super.noSuchMethod(
            Invocation.method(#updateComputer, [computer]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteComputer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComputer, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFavoriteComputer(String? id, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#setFavoriteComputer, [id], {#diverId: diverId}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> incrementDiveCount(String? id, {int? by = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#incrementDiveCount, [id], {#by: by}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateLastDownload(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastDownload, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateLastFingerprint(String? id, String? fingerprint) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastFingerprint, [id, fingerprint]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.DiveProfile>> getProfilesForDive(
    String? diveId, {
    String? computerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProfilesForDive,
              [diveId],
              {#computerId: computerId},
            ),
            returnValue: _i7.Future<List<_i11.DiveProfile>>.value(
              <_i11.DiveProfile>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i11.DiveProfile>>.value(
              <_i11.DiveProfile>[],
            ),
          )
          as _i7.Future<List<_i11.DiveProfile>>);

  @override
  _i7.Future<List<String>> getComputerIdsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerIdsForDive, [diveId]),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i3.DiveComputer>> getComputersForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getComputersForDive, [diveId]),
            returnValue: _i7.Future<List<_i3.DiveComputer>>.value(
              <_i3.DiveComputer>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i3.DiveComputer>>.value(
              <_i3.DiveComputer>[],
            ),
          )
          as _i7.Future<List<_i3.DiveComputer>>);

  @override
  _i7.Future<String?> getPrimaryComputerId(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPrimaryComputerId, [diveId]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> setPrimaryProfile(String? diveId, String? computerId) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryProfile, [diveId, computerId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> findMatchingDive({
    required DateTime? profileStartTime,
    int? toleranceMinutes = 5,
    int? durationSeconds,
    double? maxDepth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchingDive, [], {
              #profileStartTime: profileStartTime,
              #toleranceMinutes: toleranceMinutes,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
            }),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i10.DiveMatchResult?> findMatchingDiveWithScore({
    required DateTime? profileStartTime,
    int? toleranceMinutes = 5,
    int? durationSeconds,
    double? maxDepth,
    String? fingerprint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchingDiveWithScore, [], {
              #profileStartTime: profileStartTime,
              #toleranceMinutes: toleranceMinutes,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
              #fingerprint: fingerprint,
            }),
            returnValue: _i7.Future<_i10.DiveMatchResult?>.value(),
            returnValueForMissingStub:
                _i7.Future<_i10.DiveMatchResult?>.value(),
          )
          as _i7.Future<_i10.DiveMatchResult?>);

  @override
  _i7.Future<List<String>> getDiveIdsForComputer(
    String? computerId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveIdsForComputer,
              [computerId],
              {#limit: limit},
            ),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<String> importProfile({
    required String? computerId,
    required DateTime? profileStartTime,
    required List<_i10.ProfilePointData>? points,
    required int? durationSeconds,
    double? maxDepth,
    double? avgDepth,
    bool? isPrimary = false,
    String? diverId,
    List<_i10.TankData>? tanks,
    String? decoAlgorithm,
    int? gfLow,
    int? gfHigh,
    int? decoConservatism,
    List<_i10.EventData>? events,
    int? diveNumber,
    bool? forceNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importProfile, [], {
              #computerId: computerId,
              #profileStartTime: profileStartTime,
              #points: points,
              #durationSeconds: durationSeconds,
              #maxDepth: maxDepth,
              #avgDepth: avgDepth,
              #isPrimary: isPrimary,
              #diverId: diverId,
              #tanks: tanks,
              #decoAlgorithm: decoAlgorithm,
              #gfLow: gfLow,
              #gfHigh: gfHigh,
              #decoConservatism: decoConservatism,
              #events: events,
              #diveNumber: diveNumber,
              #forceNew: forceNew,
            }),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#importProfile, [], {
                  #computerId: computerId,
                  #profileStartTime: profileStartTime,
                  #points: points,
                  #durationSeconds: durationSeconds,
                  #maxDepth: maxDepth,
                  #avgDepth: avgDepth,
                  #isPrimary: isPrimary,
                  #diverId: diverId,
                  #tanks: tanks,
                  #decoAlgorithm: decoAlgorithm,
                  #gfLow: gfLow,
                  #gfHigh: gfHigh,
                  #decoConservatism: decoConservatism,
                  #events: events,
                  #diveNumber: diveNumber,
                  #forceNew: forceNew,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#importProfile, [], {
                  #computerId: computerId,
                  #profileStartTime: profileStartTime,
                  #points: points,
                  #durationSeconds: durationSeconds,
                  #maxDepth: maxDepth,
                  #avgDepth: avgDepth,
                  #isPrimary: isPrimary,
                  #diverId: diverId,
                  #tanks: tanks,
                  #decoAlgorithm: decoAlgorithm,
                  #gfLow: gfLow,
                  #gfHigh: gfHigh,
                  #decoConservatism: decoConservatism,
                  #events: events,
                  #diveNumber: diveNumber,
                  #forceNew: forceNew,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i3.DiveComputer> findOrCreateComputer({
    required String? serialNumber,
    String? diverId,
    String? manufacturer,
    String? model,
    String? connectionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreateComputer, [], {
              #serialNumber: serialNumber,
              #diverId: diverId,
              #manufacturer: manufacturer,
              #model: model,
              #connectionType: connectionType,
            }),
            returnValue: _i7.Future<_i3.DiveComputer>.value(
              _FakeDiveComputer_2(
                this,
                Invocation.method(#findOrCreateComputer, [], {
                  #serialNumber: serialNumber,
                  #diverId: diverId,
                  #manufacturer: manufacturer,
                  #model: model,
                  #connectionType: connectionType,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.DiveComputer>.value(
              _FakeDiveComputer_2(
                this,
                Invocation.method(#findOrCreateComputer, [], {
                  #serialNumber: serialNumber,
                  #diverId: diverId,
                  #manufacturer: manufacturer,
                  #model: model,
                  #connectionType: connectionType,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.DiveComputer>);

  @override
  _i7.Future<List<_i11.DiveProfileEvent>> getEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsForDive, [diveId]),
            returnValue: _i7.Future<List<_i11.DiveProfileEvent>>.value(
              <_i11.DiveProfileEvent>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i11.DiveProfileEvent>>.value(
                  <_i11.DiveProfileEvent>[],
                ),
          )
          as _i7.Future<List<_i11.DiveProfileEvent>>);

  @override
  _i7.Future<void> addProfileEvent({
    required String? diveId,
    required int? timestamp,
    required String? eventType,
    String? severity = 'info',
    String? description,
    double? depth,
    double? value,
    String? tankId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProfileEvent, [], {
              #diveId: diveId,
              #timestamp: timestamp,
              #eventType: eventType,
              #severity: severity,
              #description: description,
              #depth: depth,
              #value: value,
              #tankId: tankId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#clearEventsForDive, [diveId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [DiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveRepository extends _i1.Mock implements _i5.DiveRepository {
  @override
  _i7.Future<List<_i4.Dive>> getAllDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDives, [], {#diverId: diverId}),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<_i4.Dive?> getDiveById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveById, [id]),
            returnValue: _i7.Future<_i4.Dive?>.value(),
            returnValueForMissingStub: _i7.Future<_i4.Dive?>.value(),
          )
          as _i7.Future<_i4.Dive?>);

  @override
  _i7.Future<List<_i4.DiveProfilePoint>> getDiveProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveProfile, [diveId]),
            returnValue: _i7.Future<List<_i4.DiveProfilePoint>>.value(
              <_i4.DiveProfilePoint>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i4.DiveProfilePoint>>.value(
                  <_i4.DiveProfilePoint>[],
                ),
          )
          as _i7.Future<List<_i4.DiveProfilePoint>>);

  @override
  _i7.Future<void> saveEditedProfile(
    String? diveId,
    List<_i4.DiveProfilePoint>? editedPoints,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditedProfile, [diveId, editedPoints]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String?, List<_i4.DiveProfilePoint>>> getProfilesBySource(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesBySource, [diveId]),
            returnValue:
                _i7.Future<Map<String?, List<_i4.DiveProfilePoint>>>.value(
                  <String?, List<_i4.DiveProfilePoint>>{},
                ),
            returnValueForMissingStub:
                _i7.Future<Map<String?, List<_i4.DiveProfilePoint>>>.value(
                  <String?, List<_i4.DiveProfilePoint>>{},
                ),
          )
          as _i7.Future<Map<String?, List<_i4.DiveProfilePoint>>>);

  @override
  _i7.Future<void> restoreOriginalProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreOriginalProfile, [diveId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, List<_i4.DiveProfilePoint>>> getBatchProfileSummaries(
    List<String>? diveIds, {
    int? maxSamples = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBatchProfileSummaries,
              [diveIds],
              {#maxSamples: maxSamples},
            ),
            returnValue:
                _i7.Future<Map<String, List<_i4.DiveProfilePoint>>>.value(
                  <String, List<_i4.DiveProfilePoint>>{},
                ),
            returnValueForMissingStub:
                _i7.Future<Map<String, List<_i4.DiveProfilePoint>>>.value(
                  <String, List<_i4.DiveProfilePoint>>{},
                ),
          )
          as _i7.Future<Map<String, List<_i4.DiveProfilePoint>>>);

  @override
  _i7.Future<_i4.Dive> createDive(_i4.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#createDive, [dive]),
            returnValue: _i7.Future<_i4.Dive>.value(
              _FakeDive_3(this, Invocation.method(#createDive, [dive])),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Dive>.value(
              _FakeDive_3(this, Invocation.method(#createDive, [dive])),
            ),
          )
          as _i7.Future<_i4.Dive>);

  @override
  _i7.Future<void> updateDive(_i4.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#updateDive, [dive]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteDive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDive, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<String>> bulkDeleteDives(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteDives, [ids]),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i4.Dive>> getDivesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesByIds, [ids]),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<List<_i12.DiveSummary>> getDiveSummaries({
    String? diverId,
    _i13.DiveFilterState? filter = const _i13.DiveFilterState(),
    _i12.DiveSummaryCursor? cursor,
    int? offset,
    int? limit = 50,
    _i14.SortState<_i15.DiveSortField>? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveSummaries, [], {
              #diverId: diverId,
              #filter: filter,
              #cursor: cursor,
              #offset: offset,
              #limit: limit,
              #sort: sort,
            }),
            returnValue: _i7.Future<List<_i12.DiveSummary>>.value(
              <_i12.DiveSummary>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i12.DiveSummary>>.value(
              <_i12.DiveSummary>[],
            ),
          )
          as _i7.Future<List<_i12.DiveSummary>>);

  @override
  _i7.Future<int> getDiveCount({
    String? diverId,
    _i13.DiveFilterState? filter = const _i13.DiveFilterState(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveCount, [], {
              #diverId: diverId,
              #filter: filter,
            }),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i4.Dive>> getDivesForSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForSite, [siteId]),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<List<_i4.Dive>> getDivesForCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForCourse, [courseId]),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<List<_i4.Dive>> getDivesInRange(
    DateTime? start,
    DateTime? end, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDivesInRange,
              [start, end],
              {#diverId: diverId},
            ),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<int> getNextDiveNumber({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextDiveNumber, [], {#diverId: diverId}),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> getDiveNumberForDate(
    DateTime? dateTime, {
    String? diverId,
    int? startFrom = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveNumberForDate,
              [dateTime],
              {#diverId: diverId, #startFrom: startFrom},
            ),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i4.Dive>> searchDives(String? query, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchDives, [query], {#diverId: diverId}),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<_i5.DiveStatistics> getStatistics({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, [], {#diverId: diverId}),
            returnValue: _i7.Future<_i5.DiveStatistics>.value(
              _FakeDiveStatistics_4(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.DiveStatistics>.value(
              _FakeDiveStatistics_4(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i7.Future<_i5.DiveStatistics>);

  @override
  _i7.Future<_i5.DiveRecords> getRecords({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {#diverId: diverId}),
            returnValue: _i7.Future<_i5.DiveRecords>.value(
              _FakeDiveRecords_5(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.DiveRecords>.value(
              _FakeDiveRecords_5(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i7.Future<_i5.DiveRecords>);

  @override
  _i7.Future<Set<String>> getImportIds({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getImportIds, [], {#diverId: diverId}),
            returnValue: _i7.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i7.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i7.Future<Set<String>>);

  @override
  _i7.Future<void> toggleFavorite(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [diveId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFavorite(String? diveId, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorite, [diveId, isFavorite]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.Dive>> getFavoriteDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteDives, [], {#diverId: diverId}),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<List<_i4.Dive>> getPlannedDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedDives, [], {#diverId: diverId}),
            returnValue: _i7.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
            returnValueForMissingStub: _i7.Future<List<_i4.Dive>>.value(
              <_i4.Dive>[],
            ),
          )
          as _i7.Future<List<_i4.Dive>>);

  @override
  _i7.Future<_i4.Dive> createPlannedDive(_i4.Dive? plan) =>
      (super.noSuchMethod(
            Invocation.method(#createPlannedDive, [plan]),
            returnValue: _i7.Future<_i4.Dive>.value(
              _FakeDive_3(this, Invocation.method(#createPlannedDive, [plan])),
            ),
            returnValueForMissingStub: _i7.Future<_i4.Dive>.value(
              _FakeDive_3(this, Invocation.method(#createPlannedDive, [plan])),
            ),
          )
          as _i7.Future<_i4.Dive>);

  @override
  _i7.Future<String> convertPlanToActualDive(
    String? planId, {
    DateTime? actualDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertPlanToActualDive,
              [planId],
              {#actualDateTime: actualDateTime},
            ),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deletePlannedDive(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlannedDive, [planId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i6.GasSwitchWithTank>> getGasSwitchesForDive(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGasSwitchesForDive, [diveId]),
            returnValue: _i7.Future<List<_i6.GasSwitchWithTank>>.value(
              <_i6.GasSwitchWithTank>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i6.GasSwitchWithTank>>.value(
                  <_i6.GasSwitchWithTank>[],
                ),
          )
          as _i7.Future<List<_i6.GasSwitchWithTank>>);

  @override
  _i7.Future<_i6.GasSwitch> createGasSwitch(_i6.GasSwitch? gasSwitch) =>
      (super.noSuchMethod(
            Invocation.method(#createGasSwitch, [gasSwitch]),
            returnValue: _i7.Future<_i6.GasSwitch>.value(
              _FakeGasSwitch_6(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.GasSwitch>.value(
              _FakeGasSwitch_6(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
          )
          as _i7.Future<_i6.GasSwitch>);

  @override
  _i7.Future<void> deleteGasSwitch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitch, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteGasSwitchesForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitchesForDive, [diveId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> insertGasSwitches(List<_i6.GasSwitch>? switches) =>
      (super.noSuchMethod(
            Invocation.method(#insertGasSwitches, [switches]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.Dive?> getPreviousDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousDive, [diveId]),
            returnValue: _i7.Future<_i4.Dive?>.value(),
            returnValueForMissingStub: _i7.Future<_i4.Dive?>.value(),
          )
          as _i7.Future<_i4.Dive?>);

  @override
  _i7.Future<Duration?> getSurfaceInterval(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceInterval, [diveId]),
            returnValue: _i7.Future<Duration?>.value(),
            returnValueForMissingStub: _i7.Future<Duration?>.value(),
          )
          as _i7.Future<Duration?>);

  @override
  _i7.Future<_i5.DiveNumberingInfo> getDiveNumberingInfo({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveNumberingInfo, [], {#diverId: diverId}),
            returnValue: _i7.Future<_i5.DiveNumberingInfo>.value(
              _FakeDiveNumberingInfo_7(
                this,
                Invocation.method(#getDiveNumberingInfo, [], {
                  #diverId: diverId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.DiveNumberingInfo>.value(
              _FakeDiveNumberingInfo_7(
                this,
                Invocation.method(#getDiveNumberingInfo, [], {
                  #diverId: diverId,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.DiveNumberingInfo>);

  @override
  _i7.Future<void> renumberAllDives({int? startFrom = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#renumberAllDives, [], {#startFrom: startFrom}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> assignMissingDiveNumbers() =>
      (super.noSuchMethod(
            Invocation.method(#assignMissingDiveNumbers, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkUpdateTrip(List<String>? diveIds, String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateTrip, [diveIds, tripId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkAddTags(List<String>? diveIds, List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkAddTags, [diveIds, tagIds]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkRemoveTags(
    List<String>? diveIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkRemoveTags, [diveIds, tagIds]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i16.DiveDataSource>> getDataSources(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDataSources, [diveId]),
            returnValue: _i7.Future<List<_i16.DiveDataSource>>.value(
              <_i16.DiveDataSource>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i16.DiveDataSource>>.value(
                  <_i16.DiveDataSource>[],
                ),
          )
          as _i7.Future<List<_i16.DiveDataSource>>);

  @override
  _i7.Future<bool> hasMultipleDataSources(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#hasMultipleDataSources, [diveId]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> saveComputerReading(
    _i11.DiveDataSourcesCompanion? reading,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveComputerReading, [reading]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteComputerReading(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComputerReading, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> backfillPrimaryDataSource(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#backfillPrimaryDataSource, [diveId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> consolidateComputer({
    required String? targetDiveId,
    required _i11.DiveDataSourcesCompanion? secondaryReading,
    required List<_i11.DiveProfilesCompanion>? secondaryProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consolidateComputer, [], {
              #targetDiveId: targetDiveId,
              #secondaryReading: secondaryReading,
              #secondaryProfile: secondaryProfile,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> mergeDives({
    required String? primaryDiveId,
    required String? secondaryDiveId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeDives, [], {
              #primaryDiveId: primaryDiveId,
              #secondaryDiveId: secondaryDiveId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> unlinkComputer({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkComputer, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#unlinkComputer, [], {
                  #diveId: diveId,
                  #computerReadingId: computerReadingId,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#unlinkComputer, [], {
                  #diveId: diveId,
                  #computerReadingId: computerReadingId,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> setPrimaryDataSource({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryDataSource, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
