// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/import_wizard/data/adapters/uddf_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i34;
import 'package:submersion/core/constants/sort_options.dart' as _i33;
import 'package:submersion/core/database/database.dart' as _i36;
import 'package:submersion/core/models/sort_state.dart' as _i32;
import 'package:submersion/core/services/export/export_service.dart' as _i2;
import 'package:submersion/features/buddies/data/repositories/buddy_repository.dart'
    as _i8;
import 'package:submersion/features/buddies/domain/entities/buddy.dart' as _i24;
import 'package:submersion/features/certifications/data/repositories/certification_repository.dart'
    as _i10;
import 'package:submersion/features/certifications/domain/entities/certification.dart'
    as _i26;
import 'package:submersion/features/courses/data/repositories/course_repository.dart'
    as _i16;
import 'package:submersion/features/dive_centers/data/repositories/dive_center_repository.dart'
    as _i9;
import 'package:submersion/features/dive_centers/domain/entities/dive_center.dart'
    as _i25;
import 'package:submersion/features/dive_import/data/services/uddf_duplicate_checker.dart'
    as _i3;
import 'package:submersion/features/dive_import/data/services/uddf_entity_importer.dart'
    as _i4;
import 'package:submersion/features/dive_import/data/services/uddf_parser_service.dart'
    as _i19;
import 'package:submersion/features/dive_import/domain/services/dive_matcher.dart'
    as _i29;
import 'package:submersion/features/dive_log/data/repositories/dive_repository_impl.dart'
    as _i14;
import 'package:submersion/features/dive_log/data/repositories/tank_pressure_repository.dart'
    as _i15;
import 'package:submersion/features/dive_log/domain/entities/dive.dart' as _i17;
import 'package:submersion/features/dive_log/domain/entities/dive_computer_reading.dart'
    as _i35;
import 'package:submersion/features/dive_log/domain/entities/dive_summary.dart'
    as _i30;
import 'package:submersion/features/dive_log/domain/entities/gas_switch.dart'
    as _i18;
import 'package:submersion/features/dive_log/domain/models/dive_filter_state.dart'
    as _i31;
import 'package:submersion/features/dive_sites/data/repositories/site_repository_impl.dart'
    as _i13;
import 'package:submersion/features/dive_sites/domain/entities/dive_site.dart'
    as _i22;
import 'package:submersion/features/dive_types/data/repositories/dive_type_repository.dart'
    as _i12;
import 'package:submersion/features/dive_types/domain/entities/dive_type_entity.dart'
    as _i28;
import 'package:submersion/features/equipment/data/repositories/equipment_repository_impl.dart'
    as _i6;
import 'package:submersion/features/equipment/data/repositories/equipment_set_repository_impl.dart'
    as _i7;
import 'package:submersion/features/equipment/domain/entities/equipment_item.dart'
    as _i23;
import 'package:submersion/features/tags/data/repositories/tag_repository.dart'
    as _i11;
import 'package:submersion/features/tags/domain/entities/tag.dart' as _i27;
import 'package:submersion/features/trips/data/repositories/trip_repository.dart'
    as _i5;
import 'package:submersion/features/trips/domain/entities/trip.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUddfImportResult_0 extends _i1.SmartFake
    implements _i2.UddfImportResult {
  _FakeUddfImportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUddfDuplicateCheckResult_1 extends _i1.SmartFake
    implements _i3.UddfDuplicateCheckResult {
  _FakeUddfDuplicateCheckResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUddfEntityImportResult_2 extends _i1.SmartFake
    implements _i4.UddfEntityImportResult {
  _FakeUddfEntityImportResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripRepository_3 extends _i1.SmartFake
    implements _i5.TripRepository {
  _FakeTripRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEquipmentRepository_4 extends _i1.SmartFake
    implements _i6.EquipmentRepository {
  _FakeEquipmentRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEquipmentSetRepository_5 extends _i1.SmartFake
    implements _i7.EquipmentSetRepository {
  _FakeEquipmentSetRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBuddyRepository_6 extends _i1.SmartFake
    implements _i8.BuddyRepository {
  _FakeBuddyRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveCenterRepository_7 extends _i1.SmartFake
    implements _i9.DiveCenterRepository {
  _FakeDiveCenterRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCertificationRepository_8 extends _i1.SmartFake
    implements _i10.CertificationRepository {
  _FakeCertificationRepository_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTagRepository_9 extends _i1.SmartFake implements _i11.TagRepository {
  _FakeTagRepository_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveTypeRepository_10 extends _i1.SmartFake
    implements _i12.DiveTypeRepository {
  _FakeDiveTypeRepository_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSiteRepository_11 extends _i1.SmartFake
    implements _i13.SiteRepository {
  _FakeSiteRepository_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveRepository_12 extends _i1.SmartFake
    implements _i14.DiveRepository {
  _FakeDiveRepository_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTankPressureRepository_13 extends _i1.SmartFake
    implements _i15.TankPressureRepository {
  _FakeTankPressureRepository_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseRepository_14 extends _i1.SmartFake
    implements _i16.CourseRepository {
  _FakeCourseRepository_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDive_15 extends _i1.SmartFake implements _i17.Dive {
  _FakeDive_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveStatistics_16 extends _i1.SmartFake
    implements _i14.DiveStatistics {
  _FakeDiveStatistics_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveRecords_17 extends _i1.SmartFake implements _i14.DiveRecords {
  _FakeDiveRecords_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGasSwitch_18 extends _i1.SmartFake implements _i18.GasSwitch {
  _FakeGasSwitch_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveNumberingInfo_19 extends _i1.SmartFake
    implements _i14.DiveNumberingInfo {
  _FakeDiveNumberingInfo_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UddfParserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUddfParserService extends _i1.Mock implements _i19.UddfParserService {
  @override
  _i20.Future<_i2.UddfImportResult> parseFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#parseFile, [filePath]),
            returnValue: _i20.Future<_i2.UddfImportResult>.value(
              _FakeUddfImportResult_0(
                this,
                Invocation.method(#parseFile, [filePath]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i2.UddfImportResult>.value(
              _FakeUddfImportResult_0(
                this,
                Invocation.method(#parseFile, [filePath]),
              ),
            ),
          )
          as _i20.Future<_i2.UddfImportResult>);

  @override
  _i20.Future<_i2.UddfImportResult> parseContent(String? uddfContent) =>
      (super.noSuchMethod(
            Invocation.method(#parseContent, [uddfContent]),
            returnValue: _i20.Future<_i2.UddfImportResult>.value(
              _FakeUddfImportResult_0(
                this,
                Invocation.method(#parseContent, [uddfContent]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i2.UddfImportResult>.value(
              _FakeUddfImportResult_0(
                this,
                Invocation.method(#parseContent, [uddfContent]),
              ),
            ),
          )
          as _i20.Future<_i2.UddfImportResult>);
}

/// A class which mocks [UddfDuplicateChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockUddfDuplicateChecker extends _i1.Mock
    implements _i3.UddfDuplicateChecker {
  @override
  _i3.UddfDuplicateCheckResult check({
    required _i2.UddfImportResult? importData,
    required List<_i21.Trip>? existingTrips,
    required List<_i22.DiveSite>? existingSites,
    required List<_i23.EquipmentItem>? existingEquipment,
    required List<_i24.Buddy>? existingBuddies,
    required List<_i25.DiveCenter>? existingDiveCenters,
    required List<_i26.Certification>? existingCertifications,
    required List<_i27.Tag>? existingTags,
    required List<_i28.DiveTypeEntity>? existingDiveTypes,
    required List<_i17.Dive>? existingDives,
    _i29.DiveMatcher? matcher = const _i29.DiveMatcher(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#check, [], {
              #importData: importData,
              #existingTrips: existingTrips,
              #existingSites: existingSites,
              #existingEquipment: existingEquipment,
              #existingBuddies: existingBuddies,
              #existingDiveCenters: existingDiveCenters,
              #existingCertifications: existingCertifications,
              #existingTags: existingTags,
              #existingDiveTypes: existingDiveTypes,
              #existingDives: existingDives,
              #matcher: matcher,
            }),
            returnValue: _FakeUddfDuplicateCheckResult_1(
              this,
              Invocation.method(#check, [], {
                #importData: importData,
                #existingTrips: existingTrips,
                #existingSites: existingSites,
                #existingEquipment: existingEquipment,
                #existingBuddies: existingBuddies,
                #existingDiveCenters: existingDiveCenters,
                #existingCertifications: existingCertifications,
                #existingTags: existingTags,
                #existingDiveTypes: existingDiveTypes,
                #existingDives: existingDives,
                #matcher: matcher,
              }),
            ),
            returnValueForMissingStub: _FakeUddfDuplicateCheckResult_1(
              this,
              Invocation.method(#check, [], {
                #importData: importData,
                #existingTrips: existingTrips,
                #existingSites: existingSites,
                #existingEquipment: existingEquipment,
                #existingBuddies: existingBuddies,
                #existingDiveCenters: existingDiveCenters,
                #existingCertifications: existingCertifications,
                #existingTags: existingTags,
                #existingDiveTypes: existingDiveTypes,
                #existingDives: existingDives,
                #matcher: matcher,
              }),
            ),
          )
          as _i3.UddfDuplicateCheckResult);
}

/// A class which mocks [UddfEntityImporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockUddfEntityImporter extends _i1.Mock
    implements _i4.UddfEntityImporter {
  @override
  _i20.Future<_i4.UddfEntityImportResult> import({
    required _i2.UddfImportResult? data,
    required _i4.UddfImportSelections? selections,
    required _i4.ImportRepositories? repositories,
    required String? diverId,
    _i4.ImportProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#import, [], {
              #data: data,
              #selections: selections,
              #repositories: repositories,
              #diverId: diverId,
              #onProgress: onProgress,
            }),
            returnValue: _i20.Future<_i4.UddfEntityImportResult>.value(
              _FakeUddfEntityImportResult_2(
                this,
                Invocation.method(#import, [], {
                  #data: data,
                  #selections: selections,
                  #repositories: repositories,
                  #diverId: diverId,
                  #onProgress: onProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i20.Future<_i4.UddfEntityImportResult>.value(
                  _FakeUddfEntityImportResult_2(
                    this,
                    Invocation.method(#import, [], {
                      #data: data,
                      #selections: selections,
                      #repositories: repositories,
                      #diverId: diverId,
                      #onProgress: onProgress,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i4.UddfEntityImportResult>);
}

/// A class which mocks [ImportRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportRepositories extends _i1.Mock
    implements _i4.ImportRepositories {
  @override
  _i5.TripRepository get tripRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tripRepository),
            returnValue: _FakeTripRepository_3(
              this,
              Invocation.getter(#tripRepository),
            ),
            returnValueForMissingStub: _FakeTripRepository_3(
              this,
              Invocation.getter(#tripRepository),
            ),
          )
          as _i5.TripRepository);

  @override
  _i6.EquipmentRepository get equipmentRepository =>
      (super.noSuchMethod(
            Invocation.getter(#equipmentRepository),
            returnValue: _FakeEquipmentRepository_4(
              this,
              Invocation.getter(#equipmentRepository),
            ),
            returnValueForMissingStub: _FakeEquipmentRepository_4(
              this,
              Invocation.getter(#equipmentRepository),
            ),
          )
          as _i6.EquipmentRepository);

  @override
  _i7.EquipmentSetRepository get equipmentSetRepository =>
      (super.noSuchMethod(
            Invocation.getter(#equipmentSetRepository),
            returnValue: _FakeEquipmentSetRepository_5(
              this,
              Invocation.getter(#equipmentSetRepository),
            ),
            returnValueForMissingStub: _FakeEquipmentSetRepository_5(
              this,
              Invocation.getter(#equipmentSetRepository),
            ),
          )
          as _i7.EquipmentSetRepository);

  @override
  _i8.BuddyRepository get buddyRepository =>
      (super.noSuchMethod(
            Invocation.getter(#buddyRepository),
            returnValue: _FakeBuddyRepository_6(
              this,
              Invocation.getter(#buddyRepository),
            ),
            returnValueForMissingStub: _FakeBuddyRepository_6(
              this,
              Invocation.getter(#buddyRepository),
            ),
          )
          as _i8.BuddyRepository);

  @override
  _i9.DiveCenterRepository get diveCenterRepository =>
      (super.noSuchMethod(
            Invocation.getter(#diveCenterRepository),
            returnValue: _FakeDiveCenterRepository_7(
              this,
              Invocation.getter(#diveCenterRepository),
            ),
            returnValueForMissingStub: _FakeDiveCenterRepository_7(
              this,
              Invocation.getter(#diveCenterRepository),
            ),
          )
          as _i9.DiveCenterRepository);

  @override
  _i10.CertificationRepository get certificationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#certificationRepository),
            returnValue: _FakeCertificationRepository_8(
              this,
              Invocation.getter(#certificationRepository),
            ),
            returnValueForMissingStub: _FakeCertificationRepository_8(
              this,
              Invocation.getter(#certificationRepository),
            ),
          )
          as _i10.CertificationRepository);

  @override
  _i11.TagRepository get tagRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tagRepository),
            returnValue: _FakeTagRepository_9(
              this,
              Invocation.getter(#tagRepository),
            ),
            returnValueForMissingStub: _FakeTagRepository_9(
              this,
              Invocation.getter(#tagRepository),
            ),
          )
          as _i11.TagRepository);

  @override
  _i12.DiveTypeRepository get diveTypeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#diveTypeRepository),
            returnValue: _FakeDiveTypeRepository_10(
              this,
              Invocation.getter(#diveTypeRepository),
            ),
            returnValueForMissingStub: _FakeDiveTypeRepository_10(
              this,
              Invocation.getter(#diveTypeRepository),
            ),
          )
          as _i12.DiveTypeRepository);

  @override
  _i13.SiteRepository get siteRepository =>
      (super.noSuchMethod(
            Invocation.getter(#siteRepository),
            returnValue: _FakeSiteRepository_11(
              this,
              Invocation.getter(#siteRepository),
            ),
            returnValueForMissingStub: _FakeSiteRepository_11(
              this,
              Invocation.getter(#siteRepository),
            ),
          )
          as _i13.SiteRepository);

  @override
  _i14.DiveRepository get diveRepository =>
      (super.noSuchMethod(
            Invocation.getter(#diveRepository),
            returnValue: _FakeDiveRepository_12(
              this,
              Invocation.getter(#diveRepository),
            ),
            returnValueForMissingStub: _FakeDiveRepository_12(
              this,
              Invocation.getter(#diveRepository),
            ),
          )
          as _i14.DiveRepository);

  @override
  _i15.TankPressureRepository get tankPressureRepository =>
      (super.noSuchMethod(
            Invocation.getter(#tankPressureRepository),
            returnValue: _FakeTankPressureRepository_13(
              this,
              Invocation.getter(#tankPressureRepository),
            ),
            returnValueForMissingStub: _FakeTankPressureRepository_13(
              this,
              Invocation.getter(#tankPressureRepository),
            ),
          )
          as _i15.TankPressureRepository);

  @override
  _i16.CourseRepository get courseRepository =>
      (super.noSuchMethod(
            Invocation.getter(#courseRepository),
            returnValue: _FakeCourseRepository_14(
              this,
              Invocation.getter(#courseRepository),
            ),
            returnValueForMissingStub: _FakeCourseRepository_14(
              this,
              Invocation.getter(#courseRepository),
            ),
          )
          as _i16.CourseRepository);
}

/// A class which mocks [DiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveRepository extends _i1.Mock implements _i14.DiveRepository {
  @override
  _i20.Future<List<_i17.Dive>> getAllDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDives, [], {#diverId: diverId}),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<_i17.Dive?> getDiveById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveById, [id]),
            returnValue: _i20.Future<_i17.Dive?>.value(),
            returnValueForMissingStub: _i20.Future<_i17.Dive?>.value(),
          )
          as _i20.Future<_i17.Dive?>);

  @override
  _i20.Future<List<_i17.DiveProfilePoint>> getDiveProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveProfile, [diveId]),
            returnValue: _i20.Future<List<_i17.DiveProfilePoint>>.value(
              <_i17.DiveProfilePoint>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<_i17.DiveProfilePoint>>.value(
                  <_i17.DiveProfilePoint>[],
                ),
          )
          as _i20.Future<List<_i17.DiveProfilePoint>>);

  @override
  _i20.Future<void> saveEditedProfile(
    String? diveId,
    List<_i17.DiveProfilePoint>? editedPoints,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditedProfile, [diveId, editedPoints]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<Map<String?, List<_i17.DiveProfilePoint>>> getProfilesBySource(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesBySource, [diveId]),
            returnValue:
                _i20.Future<Map<String?, List<_i17.DiveProfilePoint>>>.value(
                  <String?, List<_i17.DiveProfilePoint>>{},
                ),
            returnValueForMissingStub:
                _i20.Future<Map<String?, List<_i17.DiveProfilePoint>>>.value(
                  <String?, List<_i17.DiveProfilePoint>>{},
                ),
          )
          as _i20.Future<Map<String?, List<_i17.DiveProfilePoint>>>);

  @override
  _i20.Future<void> restoreOriginalProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreOriginalProfile, [diveId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<Map<String, List<_i17.DiveProfilePoint>>>
  getBatchProfileSummaries(List<String>? diveIds, {int? maxSamples = 20}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBatchProfileSummaries,
              [diveIds],
              {#maxSamples: maxSamples},
            ),
            returnValue:
                _i20.Future<Map<String, List<_i17.DiveProfilePoint>>>.value(
                  <String, List<_i17.DiveProfilePoint>>{},
                ),
            returnValueForMissingStub:
                _i20.Future<Map<String, List<_i17.DiveProfilePoint>>>.value(
                  <String, List<_i17.DiveProfilePoint>>{},
                ),
          )
          as _i20.Future<Map<String, List<_i17.DiveProfilePoint>>>);

  @override
  _i20.Future<_i17.Dive> createDive(_i17.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#createDive, [dive]),
            returnValue: _i20.Future<_i17.Dive>.value(
              _FakeDive_15(this, Invocation.method(#createDive, [dive])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.Dive>.value(
              _FakeDive_15(this, Invocation.method(#createDive, [dive])),
            ),
          )
          as _i20.Future<_i17.Dive>);

  @override
  _i20.Future<void> updateDive(_i17.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#updateDive, [dive]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> deleteDive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDive, [id]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<String>> bulkDeleteDives(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteDives, [ids]),
            returnValue: _i20.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i20.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i20.Future<List<String>>);

  @override
  _i20.Future<List<_i17.Dive>> getDivesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesByIds, [ids]),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<List<_i30.DiveSummary>> getDiveSummaries({
    String? diverId,
    _i31.DiveFilterState? filter = const _i31.DiveFilterState(),
    _i30.DiveSummaryCursor? cursor,
    int? offset,
    int? limit = 50,
    _i32.SortState<_i33.DiveSortField>? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveSummaries, [], {
              #diverId: diverId,
              #filter: filter,
              #cursor: cursor,
              #offset: offset,
              #limit: limit,
              #sort: sort,
            }),
            returnValue: _i20.Future<List<_i30.DiveSummary>>.value(
              <_i30.DiveSummary>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<_i30.DiveSummary>>.value(<_i30.DiveSummary>[]),
          )
          as _i20.Future<List<_i30.DiveSummary>>);

  @override
  _i20.Future<int> getDiveCount({
    String? diverId,
    _i31.DiveFilterState? filter = const _i31.DiveFilterState(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveCount, [], {
              #diverId: diverId,
              #filter: filter,
            }),
            returnValue: _i20.Future<int>.value(0),
            returnValueForMissingStub: _i20.Future<int>.value(0),
          )
          as _i20.Future<int>);

  @override
  _i20.Future<List<_i17.Dive>> getDivesForSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForSite, [siteId]),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<List<_i17.Dive>> getDivesForCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForCourse, [courseId]),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<List<_i17.Dive>> getDivesInRange(
    DateTime? start,
    DateTime? end, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDivesInRange,
              [start, end],
              {#diverId: diverId},
            ),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<int> getNextDiveNumber({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextDiveNumber, [], {#diverId: diverId}),
            returnValue: _i20.Future<int>.value(0),
            returnValueForMissingStub: _i20.Future<int>.value(0),
          )
          as _i20.Future<int>);

  @override
  _i20.Future<int> getDiveNumberForDate(
    DateTime? dateTime, {
    String? diverId,
    int? startFrom = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveNumberForDate,
              [dateTime],
              {#diverId: diverId, #startFrom: startFrom},
            ),
            returnValue: _i20.Future<int>.value(0),
            returnValueForMissingStub: _i20.Future<int>.value(0),
          )
          as _i20.Future<int>);

  @override
  _i20.Future<List<_i17.Dive>> searchDives(String? query, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchDives, [query], {#diverId: diverId}),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<_i14.DiveStatistics> getStatistics({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, [], {#diverId: diverId}),
            returnValue: _i20.Future<_i14.DiveStatistics>.value(
              _FakeDiveStatistics_16(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i14.DiveStatistics>.value(
              _FakeDiveStatistics_16(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i20.Future<_i14.DiveStatistics>);

  @override
  _i20.Future<_i14.DiveRecords> getRecords({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {#diverId: diverId}),
            returnValue: _i20.Future<_i14.DiveRecords>.value(
              _FakeDiveRecords_17(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i14.DiveRecords>.value(
              _FakeDiveRecords_17(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i20.Future<_i14.DiveRecords>);

  @override
  _i20.Future<Set<String>> getWearableIds({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getWearableIds, [], {#diverId: diverId}),
            returnValue: _i20.Future<Set<String>>.value(<String>{}),
            returnValueForMissingStub: _i20.Future<Set<String>>.value(
              <String>{},
            ),
          )
          as _i20.Future<Set<String>>);

  @override
  _i20.Future<void> toggleFavorite(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [diveId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> setFavorite(String? diveId, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorite, [diveId, isFavorite]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i17.Dive>> getFavoriteDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteDives, [], {#diverId: diverId}),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<List<_i17.Dive>> getPlannedDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedDives, [], {#diverId: diverId}),
            returnValue: _i20.Future<List<_i17.Dive>>.value(<_i17.Dive>[]),
            returnValueForMissingStub: _i20.Future<List<_i17.Dive>>.value(
              <_i17.Dive>[],
            ),
          )
          as _i20.Future<List<_i17.Dive>>);

  @override
  _i20.Future<_i17.Dive> createPlannedDive(_i17.Dive? plan) =>
      (super.noSuchMethod(
            Invocation.method(#createPlannedDive, [plan]),
            returnValue: _i20.Future<_i17.Dive>.value(
              _FakeDive_15(this, Invocation.method(#createPlannedDive, [plan])),
            ),
            returnValueForMissingStub: _i20.Future<_i17.Dive>.value(
              _FakeDive_15(this, Invocation.method(#createPlannedDive, [plan])),
            ),
          )
          as _i20.Future<_i17.Dive>);

  @override
  _i20.Future<String> convertPlanToActualDive(
    String? planId, {
    DateTime? actualDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertPlanToActualDive,
              [planId],
              {#actualDateTime: actualDateTime},
            ),
            returnValue: _i20.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
            returnValueForMissingStub: _i20.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
          )
          as _i20.Future<String>);

  @override
  _i20.Future<void> deletePlannedDive(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlannedDive, [planId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i18.GasSwitchWithTank>> getGasSwitchesForDive(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGasSwitchesForDive, [diveId]),
            returnValue: _i20.Future<List<_i18.GasSwitchWithTank>>.value(
              <_i18.GasSwitchWithTank>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<_i18.GasSwitchWithTank>>.value(
                  <_i18.GasSwitchWithTank>[],
                ),
          )
          as _i20.Future<List<_i18.GasSwitchWithTank>>);

  @override
  _i20.Future<_i18.GasSwitch> createGasSwitch(_i18.GasSwitch? gasSwitch) =>
      (super.noSuchMethod(
            Invocation.method(#createGasSwitch, [gasSwitch]),
            returnValue: _i20.Future<_i18.GasSwitch>.value(
              _FakeGasSwitch_18(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i18.GasSwitch>.value(
              _FakeGasSwitch_18(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
          )
          as _i20.Future<_i18.GasSwitch>);

  @override
  _i20.Future<void> deleteGasSwitch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitch, [id]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> deleteGasSwitchesForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitchesForDive, [diveId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> insertGasSwitches(List<_i18.GasSwitch>? switches) =>
      (super.noSuchMethod(
            Invocation.method(#insertGasSwitches, [switches]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i17.Dive?> getPreviousDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousDive, [diveId]),
            returnValue: _i20.Future<_i17.Dive?>.value(),
            returnValueForMissingStub: _i20.Future<_i17.Dive?>.value(),
          )
          as _i20.Future<_i17.Dive?>);

  @override
  _i20.Future<Duration?> getSurfaceInterval(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceInterval, [diveId]),
            returnValue: _i20.Future<Duration?>.value(),
            returnValueForMissingStub: _i20.Future<Duration?>.value(),
          )
          as _i20.Future<Duration?>);

  @override
  _i20.Future<_i14.DiveNumberingInfo> getDiveNumberingInfo({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveNumberingInfo, [], {#diverId: diverId}),
            returnValue: _i20.Future<_i14.DiveNumberingInfo>.value(
              _FakeDiveNumberingInfo_19(
                this,
                Invocation.method(#getDiveNumberingInfo, [], {
                  #diverId: diverId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i20.Future<_i14.DiveNumberingInfo>.value(
                  _FakeDiveNumberingInfo_19(
                    this,
                    Invocation.method(#getDiveNumberingInfo, [], {
                      #diverId: diverId,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i14.DiveNumberingInfo>);

  @override
  _i20.Future<void> renumberAllDives({int? startFrom = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#renumberAllDives, [], {#startFrom: startFrom}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> assignMissingDiveNumbers() =>
      (super.noSuchMethod(
            Invocation.method(#assignMissingDiveNumbers, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> bulkUpdateTrip(List<String>? diveIds, String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateTrip, [diveIds, tripId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> bulkAddTags(List<String>? diveIds, List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkAddTags, [diveIds, tagIds]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> bulkRemoveTags(
    List<String>? diveIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkRemoveTags, [diveIds, tagIds]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i35.DiveComputerReading>> getComputerReadings(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComputerReadings, [diveId]),
            returnValue: _i20.Future<List<_i35.DiveComputerReading>>.value(
              <_i35.DiveComputerReading>[],
            ),
            returnValueForMissingStub:
                _i20.Future<List<_i35.DiveComputerReading>>.value(
                  <_i35.DiveComputerReading>[],
                ),
          )
          as _i20.Future<List<_i35.DiveComputerReading>>);

  @override
  _i20.Future<bool> hasMultipleComputers(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#hasMultipleComputers, [diveId]),
            returnValue: _i20.Future<bool>.value(false),
            returnValueForMissingStub: _i20.Future<bool>.value(false),
          )
          as _i20.Future<bool>);

  @override
  _i20.Future<void> saveComputerReading(
    _i36.DiveComputerDataCompanion? reading,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveComputerReading, [reading]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> deleteComputerReading(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComputerReading, [id]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> backfillPrimaryComputerReading(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#backfillPrimaryComputerReading, [diveId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> consolidateComputer({
    required String? targetDiveId,
    required _i36.DiveComputerDataCompanion? secondaryReading,
    required List<_i36.DiveProfilesCompanion>? secondaryProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consolidateComputer, [], {
              #targetDiveId: targetDiveId,
              #secondaryReading: secondaryReading,
              #secondaryProfile: secondaryProfile,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> mergeDives({
    required String? primaryDiveId,
    required String? secondaryDiveId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeDives, [], {
              #primaryDiveId: primaryDiveId,
              #secondaryDiveId: secondaryDiveId,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<String> unlinkComputer({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkComputer, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i20.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(#unlinkComputer, [], {
                  #diveId: diveId,
                  #computerReadingId: computerReadingId,
                }),
              ),
            ),
            returnValueForMissingStub: _i20.Future<String>.value(
              _i34.dummyValue<String>(
                this,
                Invocation.method(#unlinkComputer, [], {
                  #diveId: diveId,
                  #computerReadingId: computerReadingId,
                }),
              ),
            ),
          )
          as _i20.Future<String>);

  @override
  _i20.Future<void> setPrimaryComputer({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryComputer, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}
