import 'dart:convert';
import 'dart:math';

import 'package:crypto/crypto.dart';

/// Minimal OAuth 1.0a (RFC 5849) HMAC-SHA1 request signer.
///
/// Garmin's token endpoints are the only place in this app that speak OAuth 1,
/// and no pub package is depended on for it, so this implements just the
/// subset those two calls need: HMAC-SHA1, `Authorization` header transport,
/// consumer-only or consumer+token credentials.
///
/// Verified against `oauthlib` (a mature independent implementation) -- see
/// test/core/services/garmin_connect/garmin_oauth1_signer_test.dart, whose
/// expected signatures were generated by it rather than hand-computed.
class GarminOAuth1Signer {
  const GarminOAuth1Signer({
    required this.consumerKey,
    required this.consumerSecret,
    this.token,
    this.tokenSecret,
  });

  final String consumerKey;
  final String consumerSecret;

  /// Resource-owner token. Absent for the initial `preauthorized` call, which
  /// is signed with consumer credentials only.
  final String? token;
  final String? tokenSecret;

  /// Builds the `Authorization: OAuth ...` header value for a request.
  ///
  /// [bodyParams] must be supplied for an `application/x-www-form-urlencoded`
  /// body: RFC 5849 folds those into the signature base string alongside the
  /// query parameters, so omitting them produces a signature the server
  /// rejects.
  ///
  /// [nonce] and [timestamp] are injectable purely so tests can pin them;
  /// production callers omit both and get a fresh random nonce and the
  /// current time.
  String authorizationHeader({
    required String method,
    required Uri url,
    Map<String, String> bodyParams = const {},
    String? nonce,
    String? timestamp,
  }) {
    final oauthParams = <String, String>{
      'oauth_consumer_key': consumerKey,
      'oauth_nonce': nonce ?? _generateNonce(),
      'oauth_signature_method': 'HMAC-SHA1',
      'oauth_timestamp': timestamp ?? _generateTimestamp(),
      'oauth_version': '1.0',
      'oauth_token': ?token,
    };

    final signature = _signature(
      method: method,
      url: url,
      oauthParams: oauthParams,
      bodyParams: bodyParams,
    );

    final headerParams = <String, String>{
      ...oauthParams,
      'oauth_signature': signature,
    };

    final parts = headerParams.entries
        .map((e) => '${_encode(e.key)}="${_encode(e.value)}"')
        .join(', ');
    return 'OAuth $parts';
  }

  String _signature({
    required String method,
    required Uri url,
    required Map<String, String> oauthParams,
    required Map<String, String> bodyParams,
  }) {
    // Every oauth_* param (except the signature itself), every query
    // parameter, and every form-body parameter participate in the base string.
    final collected = <MapEntry<String, String>>[
      ...oauthParams.entries,
      ...url.queryParameters.entries,
      ...bodyParams.entries,
    ];

    // Sort by percent-encoded key, then by percent-encoded value.
    final encoded =
        collected
            .map((e) => MapEntry(_encode(e.key), _encode(e.value)))
            .toList()
          ..sort((a, b) {
            final byKey = a.key.compareTo(b.key);
            return byKey != 0 ? byKey : a.value.compareTo(b.value);
          });

    final normalizedParams = encoded
        .map((e) => '${e.key}=${e.value}')
        .join('&');

    final baseString = [
      method.toUpperCase(),
      _encode(_baseStringUri(url)),
      _encode(normalizedParams),
    ].join('&');

    final signingKey =
        '${_encode(consumerSecret)}&${_encode(tokenSecret ?? '')}';

    final digest = Hmac(
      sha1,
      utf8.encode(signingKey),
    ).convert(utf8.encode(baseString));
    return base64.encode(digest.bytes);
  }

  /// Scheme and authority lowercased, default port dropped, query and
  /// fragment removed -- the "base string URI" of RFC 5849 section 3.4.1.2.
  static String _baseStringUri(Uri url) {
    final scheme = url.scheme.toLowerCase();
    final host = url.host.toLowerCase();
    final isDefaultPort =
        (scheme == 'http' && url.port == 80) ||
        (scheme == 'https' && url.port == 443);
    final authority = isDefaultPort ? host : '$host:${url.port}';
    final path = url.path.isEmpty ? '/' : url.path;
    return '$scheme://$authority$path';
  }

  /// RFC 3986 percent-encoding. Dart's [Uri.encodeComponent] leaves `!*'()`
  /// unescaped, which OAuth requires escaped, so the unreserved set is
  /// applied explicitly here rather than patching up its output.
  static String _encode(String value) {
    const unreserved =
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        'abcdefghijklmnopqrstuvwxyz'
        '0123456789-._~';
    final buffer = StringBuffer();
    for (final byte in utf8.encode(value)) {
      final char = String.fromCharCode(byte);
      if (byte < 128 && unreserved.contains(char)) {
        buffer.write(char);
      } else {
        buffer.write(
          '%${byte.toRadixString(16).toUpperCase().padLeft(2, '0')}',
        );
      }
    }
    return buffer.toString();
  }

  static String _generateNonce() {
    final random = Random.secure();
    return List.generate(
      32,
      (_) => '0123456789abcdef'[random.nextInt(16)],
    ).join();
  }

  static String _generateTimestamp() =>
      (DateTime.now().millisecondsSinceEpoch ~/ 1000).toString();
}
