// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/dive_import/presentation/providers/dive_import_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:submersion/features/dive_import/domain/entities/imported_dive.dart'
    as _i8;
import 'package:submersion/features/dive_import/domain/services/health_import_service.dart'
    as _i7;
import 'package:submersion/features/dive_log/data/repositories/dive_repository_impl.dart'
    as _i3;
import 'package:submersion/features/dive_log/domain/entities/dive.dart' as _i2;
import 'package:submersion/features/dive_log/domain/entities/gas_switch.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDive_0 extends _i1.SmartFake implements _i2.Dive {
  _FakeDive_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveStatistics_1 extends _i1.SmartFake
    implements _i3.DiveStatistics {
  _FakeDiveStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveRecords_2 extends _i1.SmartFake implements _i3.DiveRecords {
  _FakeDiveRecords_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGasSwitch_3 extends _i1.SmartFake implements _i4.GasSwitch {
  _FakeGasSwitch_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveNumberingInfo_4 extends _i1.SmartFake
    implements _i3.DiveNumberingInfo {
  _FakeDiveNumberingInfo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveRepository extends _i1.Mock implements _i3.DiveRepository {
  MockDiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Dive>> getAllDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDives, [], {#diverId: diverId}),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<_i2.Dive?> getDiveById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveById, [id]),
            returnValue: _i5.Future<_i2.Dive?>.value(),
          )
          as _i5.Future<_i2.Dive?>);

  @override
  _i5.Future<List<_i2.DiveProfilePoint>> getDiveProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveProfile, [diveId]),
            returnValue: _i5.Future<List<_i2.DiveProfilePoint>>.value(
              <_i2.DiveProfilePoint>[],
            ),
          )
          as _i5.Future<List<_i2.DiveProfilePoint>>);

  @override
  _i5.Future<_i2.Dive> createDive(_i2.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#createDive, [dive]),
            returnValue: _i5.Future<_i2.Dive>.value(
              _FakeDive_0(this, Invocation.method(#createDive, [dive])),
            ),
          )
          as _i5.Future<_i2.Dive>);

  @override
  _i5.Future<void> updateDive(_i2.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#updateDive, [dive]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDive, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<String>> bulkDeleteDives(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteDives, [ids]),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i2.Dive>> getDivesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesByIds, [ids]),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<List<_i2.Dive>> getDivesForSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForSite, [siteId]),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<List<_i2.Dive>> getDivesForCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForCourse, [courseId]),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<List<_i2.Dive>> getDivesInRange(
    DateTime? start,
    DateTime? end, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDivesInRange,
              [start, end],
              {#diverId: diverId},
            ),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<int> getNextDiveNumber({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextDiveNumber, [], {#diverId: diverId}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getDiveNumberForDate(
    DateTime? dateTime, {
    String? diverId,
    int? startFrom = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveNumberForDate,
              [dateTime],
              {#diverId: diverId, #startFrom: startFrom},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.Dive>> searchDives(String? query, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchDives, [query], {#diverId: diverId}),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<_i3.DiveStatistics> getStatistics({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, [], {#diverId: diverId}),
            returnValue: _i5.Future<_i3.DiveStatistics>.value(
              _FakeDiveStatistics_1(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i5.Future<_i3.DiveStatistics>);

  @override
  _i5.Future<_i3.DiveRecords> getRecords({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {#diverId: diverId}),
            returnValue: _i5.Future<_i3.DiveRecords>.value(
              _FakeDiveRecords_2(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i5.Future<_i3.DiveRecords>);

  @override
  _i5.Future<Set<String>> getWearableIds({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getWearableIds, [], {#diverId: diverId}),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<void> toggleFavorite(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [diveId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setFavorite(String? diveId, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorite, [diveId, isFavorite]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Dive>> getFavoriteDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteDives, [], {#diverId: diverId}),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<List<_i2.Dive>> getPlannedDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedDives, [], {#diverId: diverId}),
            returnValue: _i5.Future<List<_i2.Dive>>.value(<_i2.Dive>[]),
          )
          as _i5.Future<List<_i2.Dive>>);

  @override
  _i5.Future<_i2.Dive> createPlannedDive(_i2.Dive? plan) =>
      (super.noSuchMethod(
            Invocation.method(#createPlannedDive, [plan]),
            returnValue: _i5.Future<_i2.Dive>.value(
              _FakeDive_0(this, Invocation.method(#createPlannedDive, [plan])),
            ),
          )
          as _i5.Future<_i2.Dive>);

  @override
  _i5.Future<String> convertPlanToActualDive(
    String? planId, {
    DateTime? actualDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertPlanToActualDive,
              [planId],
              {#actualDateTime: actualDateTime},
            ),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deletePlannedDive(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlannedDive, [planId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.GasSwitchWithTank>> getGasSwitchesForDive(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGasSwitchesForDive, [diveId]),
            returnValue: _i5.Future<List<_i4.GasSwitchWithTank>>.value(
              <_i4.GasSwitchWithTank>[],
            ),
          )
          as _i5.Future<List<_i4.GasSwitchWithTank>>);

  @override
  _i5.Future<_i4.GasSwitch> createGasSwitch(_i4.GasSwitch? gasSwitch) =>
      (super.noSuchMethod(
            Invocation.method(#createGasSwitch, [gasSwitch]),
            returnValue: _i5.Future<_i4.GasSwitch>.value(
              _FakeGasSwitch_3(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
          )
          as _i5.Future<_i4.GasSwitch>);

  @override
  _i5.Future<void> deleteGasSwitch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitch, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteGasSwitchesForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitchesForDive, [diveId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> insertGasSwitches(List<_i4.GasSwitch>? switches) =>
      (super.noSuchMethod(
            Invocation.method(#insertGasSwitches, [switches]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Dive?> getPreviousDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousDive, [diveId]),
            returnValue: _i5.Future<_i2.Dive?>.value(),
          )
          as _i5.Future<_i2.Dive?>);

  @override
  _i5.Future<Duration?> getSurfaceInterval(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceInterval, [diveId]),
            returnValue: _i5.Future<Duration?>.value(),
          )
          as _i5.Future<Duration?>);

  @override
  _i5.Future<_i3.DiveNumberingInfo> getDiveNumberingInfo({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveNumberingInfo, [], {#diverId: diverId}),
            returnValue: _i5.Future<_i3.DiveNumberingInfo>.value(
              _FakeDiveNumberingInfo_4(
                this,
                Invocation.method(#getDiveNumberingInfo, [], {
                  #diverId: diverId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.DiveNumberingInfo>);

  @override
  _i5.Future<void> renumberAllDives({int? startFrom = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#renumberAllDives, [], {#startFrom: startFrom}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> assignMissingDiveNumbers() =>
      (super.noSuchMethod(
            Invocation.method(#assignMissingDiveNumbers, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> bulkUpdateTrip(List<String>? diveIds, String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateTrip, [diveIds, tripId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> bulkAddTags(List<String>? diveIds, List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkAddTags, [diveIds, tagIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> bulkRemoveTags(
    List<String>? diveIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkRemoveTags, [diveIds, tagIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [HealthImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthImportService extends _i1.Mock
    implements _i7.HealthImportService {
  MockHealthImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ImportSource get source =>
      (super.noSuchMethod(
            Invocation.getter(#source),
            returnValue: _i8.ImportSource.appleWatch,
          )
          as _i8.ImportSource);

  @override
  _i5.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermissions, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i8.ImportedDive>> fetchDives({
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDives, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i5.Future<List<_i8.ImportedDive>>.value(
              <_i8.ImportedDive>[],
            ),
          )
          as _i5.Future<List<_i8.ImportedDive>>);

  @override
  _i5.Future<List<_i8.ImportedProfileSample>> fetchDiveProfile(
    String? sourceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiveProfile, [sourceId]),
            returnValue: _i5.Future<List<_i8.ImportedProfileSample>>.value(
              <_i8.ImportedProfileSample>[],
            ),
          )
          as _i5.Future<List<_i8.ImportedProfileSample>>);
}
