import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/src/species_tool_support.dart';

void main() {
  final rows = [
    {'id': 'sp_a_fish', 'commonName': 'A Fish', 'description': 'Desc A'},
    {'id': 'sp_b_ray', 'commonName': 'B Ray', 'description': 'Desc B'},
  ];

  test('speciesSlug strips the prefix and rejects other ids', () {
    expect(speciesSlug('sp_whale_shark'), 'whale_shark');
    expect(() => speciesSlug('whale_shark'), throwsFormatException);
    expect(() => speciesSlug('sp_Whale'), throwsFormatException);
  });

  test('renderNameLookup emits one case per row inside the switch', () {
    final source = renderNameLookup(rows);

    expect(
      source,
      contains('// GENERATED by tool/generate_species_lookups.dart'),
    );
    expect(
      source,
      contains(
        'String? builtInSpeciesName(AppLocalizations l10n, String id) =>',
      ),
    );
    expect(source, contains("  'sp_a_fish' => l10n.species_a_fish_name,\n"));
    expect(source, contains("  'sp_b_ray' => l10n.species_b_ray_name,\n"));
    expect(source, contains('  _ => null,\n};\n'));
    // Two cases plus the doc comment's mention of the `sp_` slug.
    expect('sp_'.allMatches(source).length, 3);
  });

  test('renderDescriptionLookup mirrors the name renderer with _desc', () {
    final source = renderDescriptionLookup(rows);

    expect(source, contains("  'sp_a_fish' => l10n.species_a_fish_desc,\n"));
    expect(source, contains('String? builtInSpeciesDescription('));
  });

  test('insertSpeciesArbKeys lands after the last species_*_desc key', () {
    const arb = '''
{
  "@@locale": "en",
  "species_whale_shark_name": "Whale Shark",
  "species_whale_shark_desc": "Big.",
  "common_action_done": "Done"
}
''';
    final out = insertSpeciesArbKeys(arb, [
      const ArbSpeciesEntry(
        id: 'sp_a_fish',
        name: 'A Fish',
        description: 'Desc "A"',
      ),
    ]);

    final lines = out.split('\n');
    final descAt = lines.indexWhere(
      (l) => l.contains('"species_whale_shark_desc"'),
    );
    expect(lines[descAt + 1], '  "species_a_fish_name": "A Fish",');
    expect(lines[descAt + 2], '  "species_a_fish_desc": "Desc \\"A\\"",');
    expect(lines[descAt + 3], '  "common_action_done": "Done"');
    expect(jsonDecode(out), isA<Map<String, dynamic>>());
  });

  test('insertSpeciesArbKeys refuses an existing key', () {
    const arb =
        '{\n  "species_whale_shark_name": "W",\n'
        '  "species_whale_shark_desc": "B"\n}\n';
    expect(
      () => insertSpeciesArbKeys(arb, [
        const ArbSpeciesEntry(
          id: 'sp_whale_shark',
          name: 'x',
          description: 'y',
        ),
      ]),
      throwsStateError,
    );
  });

  test('localizedNamesFromTaxon picks the top valid name per locale', () async {
    final json =
        jsonDecode(
              await File(
                'test/fixtures/inaturalist/taxa_esox_lucius_all_names.json',
              ).readAsString(),
            )
            as Map<String, dynamic>;
    final taxon = (json['results'] as List).first as Map<String, dynamic>;

    final names = localizedNamesFromTaxon(taxon, englishFallback: 'Pike');

    expect(names['en'], 'Northern Pike');
    // Position 0 beats the alternative German name at position 56.
    expect(names['de'], 'Hecht');
    // Simplified (zh-CN) is preferred over the traditional zh entry.
    expect(names['zh'], '白斑狗鱼');
    expect(names['pt'], 'Lúcio');
    // Absent locale: the taxon's English name, not the seed fallback.
    expect(names['ar'], 'Northern Pike');
    expect(names.keys.toSet(), appLocales.toSet());
  });

  test('localizedNamesFromTaxon falls back to the seed name', () {
    final names = localizedNamesFromTaxon({
      'name': 'Esox lucius',
    }, englishFallback: 'Pike');

    expect(names['en'], 'Pike');
    expect(names['he'], 'Pike');
  });

  test('applyCuratedNames restores the seed English and honours overrides', () {
    final names = {
      'en': 'Florida Bass',
      'de': 'Forellenbarsch',
      'he': 'Florida Bass',
      'ar': 'Florida Bass',
    };

    final out = applyCuratedNames(
      names,
      'Largemouth Bass',
      overrides: {'he': 'בס גדול פה'},
    );

    expect(out['en'], 'Largemouth Bass');
    expect(out['de'], 'Forellenbarsch');
    expect(out['ar'], 'Largemouth Bass');
    expect(out['he'], 'בס גדול פה');
  });
}
