// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/media/presentation/widgets/url_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:submersion/core/database/database.dart' as _i6;
import 'package:submersion/features/media/data/repositories/media_repository.dart'
    as _i7;
import 'package:submersion/features/media/data/services/network_credentials_service.dart'
    as _i5;
import 'package:submersion/features/media/data/services/network_fetch_pipeline.dart'
    as _i3;
import 'package:submersion/features/media/domain/entities/media_item.dart'
    as _i2;
import 'package:submersion/features/media/domain/entities/media_source_type.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMediaItem_0 extends _i1.SmartFake implements _i2.MediaItem {
  _FakeMediaItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkFetchPipeline].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkFetchPipeline extends _i1.Mock
    implements _i3.NetworkFetchPipeline {
  MockNetworkFetchPipeline() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> ingest(List<Uri>? urls, {bool? autoMatch = true}) =>
      (super.noSuchMethod(
            Invocation.method(#ingest, [urls], {#autoMatch: autoMatch}),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> idle() =>
      (super.noSuchMethod(
            Invocation.method(#idle, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkCredentialsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkCredentialsService extends _i1.Mock
    implements _i5.NetworkCredentialsService {
  MockNetworkCredentialsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save({
    required String? hostname,
    required String? authType,
    String? username,
    String? password,
    String? token,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#save, [], {
              #hostname: hostname,
              #authType: authType,
              #username: username,
              #password: password,
              #token: token,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>?> headersFor(Uri? uri) =>
      (super.noSuchMethod(
            Invocation.method(#headersFor, [uri]),
            returnValue: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.NetworkCredentialHost>> list() =>
      (super.noSuchMethod(
            Invocation.method(#list, []),
            returnValue: _i4.Future<List<_i6.NetworkCredentialHost>>.value(
              <_i6.NetworkCredentialHost>[],
            ),
          )
          as _i4.Future<List<_i6.NetworkCredentialHost>>);
}

/// A class which mocks [MediaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaRepository extends _i1.Mock implements _i7.MediaRepository {
  MockMediaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.MediaItem>> getMediaForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaForDive, [diveId]),
            returnValue: _i4.Future<List<_i2.MediaItem>>.value(
              <_i2.MediaItem>[],
            ),
          )
          as _i4.Future<List<_i2.MediaItem>>);

  @override
  _i4.Future<_i2.MediaItem?> getMediaById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaById, [id]),
            returnValue: _i4.Future<_i2.MediaItem?>.value(),
          )
          as _i4.Future<_i2.MediaItem?>);

  @override
  _i4.Future<_i2.MediaItem> createMedia(_i2.MediaItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#createMedia, [item]),
            returnValue: _i4.Future<_i2.MediaItem>.value(
              _FakeMediaItem_0(this, Invocation.method(#createMedia, [item])),
            ),
          )
          as _i4.Future<_i2.MediaItem>);

  @override
  _i4.Future<void> updateMedia(_i2.MediaItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateMedia, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMedia(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMedia, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMultipleMedia(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultipleMedia, [ids]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markAsOrphaned(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsOrphaned, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markAsVerified(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsVerified, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MediaItem>> getAllBySourceType(
    _i8.MediaSourceType? sourceType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBySourceType, [sourceType]),
            returnValue: _i4.Future<List<_i2.MediaItem>>.value(
              <_i2.MediaItem>[],
            ),
          )
          as _i4.Future<List<_i2.MediaItem>>);

  @override
  _i4.Future<List<_i2.MediaItem>> getOrphanedMedia() =>
      (super.noSuchMethod(
            Invocation.method(#getOrphanedMedia, []),
            returnValue: _i4.Future<List<_i2.MediaItem>>.value(
              <_i2.MediaItem>[],
            ),
          )
          as _i4.Future<List<_i2.MediaItem>>);

  @override
  _i4.Future<int> deleteOrphanedMedia() =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrphanedMedia, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.MediaEnrichment?> getEnrichmentForMedia(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrichmentForMedia, [mediaId]),
            returnValue: _i4.Future<_i2.MediaEnrichment?>.value(),
          )
          as _i4.Future<_i2.MediaEnrichment?>);

  @override
  _i4.Future<void> saveEnrichment(_i2.MediaEnrichment? enrichment) =>
      (super.noSuchMethod(
            Invocation.method(#saveEnrichment, [enrichment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getMediaCountForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaCountForDive, [diveId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Set<String>> getLinkedAssetIdsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedAssetIdsForDive, [diveId]),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<List<({double latitude, double longitude, DateTime takenAt})>>
  getGpsFromDiveMedia(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getGpsFromDiveMedia, [diveId]),
            returnValue:
                _i4.Future<
                  List<({double latitude, double longitude, DateTime takenAt})>
                >.value(
                  <({double latitude, double longitude, DateTime takenAt})>[],
                ),
          )
          as _i4.Future<
            List<({double latitude, double longitude, DateTime takenAt})>
          >);

  @override
  _i4.Future<({double latitude, double longitude})?> getBestGpsFromDiveMedia(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBestGpsFromDiveMedia, [diveId]),
            returnValue:
                _i4.Future<({double latitude, double longitude})?>.value(),
          )
          as _i4.Future<({double latitude, double longitude})?>);

  @override
  _i4.Future<int> getPendingSuggestionCount(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSuggestionCount, [diveId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
