// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/import_wizard/presentation/providers/import_wizard_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:submersion/features/import_wizard/domain/adapters/import_source_adapter.dart'
    as _i4;
import 'package:submersion/features/import_wizard/domain/models/duplicate_action.dart'
    as _i7;
import 'package:submersion/features/import_wizard/domain/models/import_bundle.dart'
    as _i2;
import 'package:submersion/features/import_wizard/domain/models/unified_import_result.dart'
    as _i3;
import 'package:submersion/features/import_wizard/domain/models/wizard_step_def.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImportBundle_0 extends _i1.SmartFake implements _i2.ImportBundle {
  _FakeImportBundle_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnifiedImportResult_1 extends _i1.SmartFake
    implements _i3.UnifiedImportResult {
  _FakeUnifiedImportResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImportSourceAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportSourceAdapter extends _i1.Mock
    implements _i4.ImportSourceAdapter {
  @override
  _i2.ImportSourceType get sourceType =>
      (super.noSuchMethod(
            Invocation.getter(#sourceType),
            returnValue: _i2.ImportSourceType.uddf,
            returnValueForMissingStub: _i2.ImportSourceType.uddf,
          )
          as _i2.ImportSourceType);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  List<_i6.WizardStepDef> get acquisitionSteps =>
      (super.noSuchMethod(
            Invocation.getter(#acquisitionSteps),
            returnValue: <_i6.WizardStepDef>[],
            returnValueForMissingStub: <_i6.WizardStepDef>[],
          )
          as List<_i6.WizardStepDef>);

  @override
  Set<_i7.DuplicateAction> get supportedDuplicateActions =>
      (super.noSuchMethod(
            Invocation.getter(#supportedDuplicateActions),
            returnValue: <_i7.DuplicateAction>{},
            returnValueForMissingStub: <_i7.DuplicateAction>{},
          )
          as Set<_i7.DuplicateAction>);

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i2.ImportBundle> buildBundle() =>
      (super.noSuchMethod(
            Invocation.method(#buildBundle, []),
            returnValue: _i8.Future<_i2.ImportBundle>.value(
              _FakeImportBundle_0(this, Invocation.method(#buildBundle, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.ImportBundle>.value(
              _FakeImportBundle_0(this, Invocation.method(#buildBundle, [])),
            ),
          )
          as _i8.Future<_i2.ImportBundle>);

  @override
  _i8.Future<_i2.ImportBundle> checkDuplicates(_i2.ImportBundle? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#checkDuplicates, [bundle]),
            returnValue: _i8.Future<_i2.ImportBundle>.value(
              _FakeImportBundle_0(
                this,
                Invocation.method(#checkDuplicates, [bundle]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.ImportBundle>.value(
              _FakeImportBundle_0(
                this,
                Invocation.method(#checkDuplicates, [bundle]),
              ),
            ),
          )
          as _i8.Future<_i2.ImportBundle>);

  @override
  _i8.Future<_i3.UnifiedImportResult> performImport(
    _i2.ImportBundle? bundle,
    Map<_i2.ImportEntityType, Set<int>>? selections,
    Map<_i2.ImportEntityType, Map<int, _i7.DuplicateAction>>?
    duplicateActions, {
    bool? retainSourceDiveNumbers,
    void Function(String, int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #performImport,
              [bundle, selections, duplicateActions],
              {
                #retainSourceDiveNumbers: retainSourceDiveNumbers,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i8.Future<_i3.UnifiedImportResult>.value(
              _FakeUnifiedImportResult_1(
                this,
                Invocation.method(
                  #performImport,
                  [bundle, selections, duplicateActions],
                  {
                    #retainSourceDiveNumbers: retainSourceDiveNumbers,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.UnifiedImportResult>.value(
                  _FakeUnifiedImportResult_1(
                    this,
                    Invocation.method(
                      #performImport,
                      [bundle, selections, duplicateActions],
                      {
                        #retainSourceDiveNumbers: retainSourceDiveNumbers,
                        #onProgress: onProgress,
                      },
                    ),
                  ),
                ),
          )
          as _i8.Future<_i3.UnifiedImportResult>);
}
