import 'dart:io';

import 'package:equatable/equatable.dart';
import 'package:uuid/uuid.dart';

import 'package:submersion/core/providers/provider.dart';
import 'package:submersion/features/media/data/repositories/media_repository.dart';
import 'package:submersion/features/media/data/services/local_bookmark_storage.dart';
import 'package:submersion/features/media/data/services/local_media_platform.dart';
import 'package:submersion/features/media/domain/entities/media_item.dart';
import 'package:submersion/features/media/domain/entities/media_source_type.dart';
import 'package:submersion/features/media/domain/value_objects/extracted_file.dart';
import 'package:submersion/features/media/domain/value_objects/matched_selection.dart';
import 'package:submersion/features/media/presentation/providers/media_providers.dart';
import 'package:submersion/features/media/presentation/providers/media_resolver_providers.dart';

/// State for the Files tab in the photo picker.
///
/// Holds the picked + EXIF-extracted files, the matcher's assignment of
/// each to a dive (or unmatched), the auto-match toggle preference, and
/// extraction progress for the UI's progress indicator.
class FilesTabState extends Equatable {
  final List<ExtractedFile> files;
  final bool autoMatchByDate;
  final bool isExtracting;
  final int extractedCount;
  final int totalToExtract;
  final MatchedSelection match;

  const FilesTabState({
    required this.files,
    required this.autoMatchByDate,
    required this.isExtracting,
    required this.extractedCount,
    required this.totalToExtract,
    required this.match,
  });

  factory FilesTabState.initial() => FilesTabState(
    files: const [],
    autoMatchByDate: true,
    isExtracting: false,
    extractedCount: 0,
    totalToExtract: 0,
    match: MatchedSelection.empty(),
  );

  FilesTabState copyWith({
    List<ExtractedFile>? files,
    bool? autoMatchByDate,
    bool? isExtracting,
    int? extractedCount,
    int? totalToExtract,
    MatchedSelection? match,
  }) => FilesTabState(
    files: files ?? this.files,
    autoMatchByDate: autoMatchByDate ?? this.autoMatchByDate,
    isExtracting: isExtracting ?? this.isExtracting,
    extractedCount: extractedCount ?? this.extractedCount,
    totalToExtract: totalToExtract ?? this.totalToExtract,
    match: match ?? this.match,
  );

  @override
  List<Object?> get props => [
    files,
    autoMatchByDate,
    isExtracting,
    extractedCount,
    totalToExtract,
    match,
  ];
}

/// Notifier for the Files tab.
///
/// Phase 2 actions: [toggleAutoMatch], [clear], [setFiles],
/// [setExtractionProgress], [removeFile], [commit], [undoCommit].
///
/// [commit] iterates the matcher's assignment and persists each
/// [ExtractedFile] as a [MediaItem] row via [MediaRepository.createMedia].
/// On iOS / macOS it first creates a security-scoped bookmark blob via
/// [LocalMediaPlatform.createBookmark] and stores it in the keychain via
/// [LocalBookmarkStorage.write] keyed by a freshly-generated UUID; that
/// UUID becomes the row's `bookmarkRef`. On Android it round-trips the
/// picker URI through [LocalMediaPlatform.takePersistableUri] and stores
/// the returned URI string as `bookmarkRef`. On desktop it stores the
/// absolute filesystem path in `localPath` instead.
///
/// Unmatched files are skipped — assignment UI for them is Phase 3.
///
/// [undoCommit] takes the list of IDs returned by [commit] and deletes
/// each row. The keychain bookmark blob (if any) is intentionally left
/// orphaned per the Phase 2 spec — without it nothing references the
/// blob, and a future maintenance pass can sweep them.
class FilesTabNotifier extends StateNotifier<FilesTabState> {
  FilesTabNotifier({
    required this.mediaRepository,
    required this.bookmarkStorage,
    required this.platform,
  }) : super(FilesTabState.initial());

  final MediaRepository mediaRepository;
  final LocalBookmarkStorage bookmarkStorage;
  final LocalMediaPlatform platform;

  /// Used solely to generate the per-file `bookmarkRef` key on iOS / macOS.
  /// The MediaItem row's primary key is generated by [MediaRepository] itself.
  static const _uuid = Uuid();

  void toggleAutoMatch() {
    state = state.copyWith(autoMatchByDate: !state.autoMatchByDate);
  }

  void clear() {
    state = FilesTabState.initial();
  }

  void setFiles(List<ExtractedFile> files, {required MatchedSelection match}) {
    state = state.copyWith(files: files, match: match);
  }

  void setExtractionProgress({required int done, required int total}) {
    state = state.copyWith(
      isExtracting: total > 0 && done < total,
      extractedCount: done,
      totalToExtract: total,
    );
  }

  void removeFile(String sourcePath) {
    final remaining = state.files
        .where((f) => f.sourcePath != sourcePath)
        .toList();
    state = state.copyWith(files: remaining);
  }

  /// Persists the matcher's per-dive assignment as [MediaItem] rows and
  /// returns the list of created IDs. Pass the list back to [undoCommit]
  /// to roll back. State is reset via [clear] before returning.
  Future<List<String>> commit() async {
    final created = <String>[];
    for (final entry in state.match.matched.entries) {
      for (final file in entry.value) {
        final id = await _persistOne(file, entry.key);
        if (id != null) created.add(id);
      }
    }
    clear();
    return created;
  }

  /// Reverses a prior [commit] by deleting each row by id. Bookmark blobs
  /// in the keychain are intentionally not cleaned up — see class doc.
  Future<void> undoCommit(List<String> ids) async {
    for (final id in ids) {
      await mediaRepository.deleteMedia(id);
    }
  }

  Future<String?> _persistOne(ExtractedFile file, String diveId) async {
    String? localPath;
    String? bookmarkRef;

    if (Platform.isIOS || Platform.isMacOS) {
      final blob = await platform.createBookmark(file.file.path);
      bookmarkRef = _uuid.v4();
      await bookmarkStorage.write(bookmarkRef, blob);
    } else if (Platform.isAndroid) {
      // file.file.path on Android may already be a content URI from
      // file_picker. takePersistableUri makes it durable across reboots.
      bookmarkRef = await platform.takePersistableUri(file.file.path);
    } else {
      localPath = file.file.path;
    }

    final now = DateTime.now();
    final item = MediaItem(
      // Empty id triggers UUID generation in MediaRepository.createMedia.
      id: '',
      diveId: diveId,
      mediaType: file.metadata.mimeType.startsWith('video/')
          ? MediaType.video
          : MediaType.photo,
      sourceType: MediaSourceType.localFile,
      localPath: localPath,
      bookmarkRef: bookmarkRef,
      takenAt: file.metadata.takenAt ?? now,
      latitude: file.metadata.latitude,
      longitude: file.metadata.longitude,
      width: file.metadata.width,
      height: file.metadata.height,
      durationSeconds: file.metadata.durationSeconds,
      createdAt: now,
      updatedAt: now,
    );

    final saved = await mediaRepository.createMedia(item);
    return saved.id;
  }
}

final filesTabNotifierProvider =
    StateNotifierProvider<FilesTabNotifier, FilesTabState>(
      (ref) => FilesTabNotifier(
        mediaRepository: ref.read(mediaRepositoryProvider),
        bookmarkStorage: ref.read(localBookmarkStorageProvider),
        platform: ref.read(localMediaPlatformProvider),
      ),
    );
