// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/dive_sites/presentation/providers/site_match_review_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:submersion/core/constants/sort_options.dart' as _i13;
import 'package:submersion/core/database/database.dart' as _i9;
import 'package:submersion/core/models/sort_state.dart' as _i12;
import 'package:submersion/features/dive_log/data/repositories/dive_repository_impl.dart'
    as _i5;
import 'package:submersion/features/dive_log/domain/entities/dive.dart' as _i4;
import 'package:submersion/features/dive_log/domain/entities/dive_data_source.dart'
    as _i16;
import 'package:submersion/features/dive_log/domain/entities/dive_summary.dart'
    as _i10;
import 'package:submersion/features/dive_log/domain/entities/gas_switch.dart'
    as _i6;
import 'package:submersion/features/dive_log/domain/entities/profile_event.dart'
    as _i15;
import 'package:submersion/features/dive_log/domain/models/dive_filter_state.dart'
    as _i11;
import 'package:submersion/features/dive_sites/data/repositories/site_repository_impl.dart'
    as _i7;
import 'package:submersion/features/dive_sites/data/services/dive_site_api_service.dart'
    as _i3;
import 'package:submersion/features/dive_sites/domain/entities/dive_site.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDiveSite_0 extends _i1.SmartFake implements _i2.DiveSite {
  _FakeDiveSite_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveSiteSearchResult_1 extends _i1.SmartFake
    implements _i3.DiveSiteSearchResult {
  _FakeDiveSiteSearchResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDive_2 extends _i1.SmartFake implements _i4.Dive {
  _FakeDive_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveStatistics_3 extends _i1.SmartFake
    implements _i5.DiveStatistics {
  _FakeDiveStatistics_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveRecords_4 extends _i1.SmartFake implements _i5.DiveRecords {
  _FakeDiveRecords_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGasSwitch_5 extends _i1.SmartFake implements _i6.GasSwitch {
  _FakeGasSwitch_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDiveNumberingInfo_6 extends _i1.SmartFake
    implements _i5.DiveNumberingInfo {
  _FakeDiveNumberingInfo_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SiteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSiteRepository extends _i1.Mock implements _i7.SiteRepository {
  MockSiteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.DiveSite>> getAllSites({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSites, [], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i2.DiveSite>>.value(<_i2.DiveSite>[]),
          )
          as _i8.Future<List<_i2.DiveSite>>);

  @override
  _i8.Stream<void> watchSitesChanges() =>
      (super.noSuchMethod(
            Invocation.method(#watchSitesChanges, []),
            returnValue: _i8.Stream<void>.empty(),
          )
          as _i8.Stream<void>);

  @override
  _i8.Future<_i2.DiveSite?> getSiteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSiteById, [id]),
            returnValue: _i8.Future<_i2.DiveSite?>.value(),
          )
          as _i8.Future<_i2.DiveSite?>);

  @override
  _i8.Future<_i2.DiveSite> createSite(_i2.DiveSite? site) =>
      (super.noSuchMethod(
            Invocation.method(#createSite, [site]),
            returnValue: _i8.Future<_i2.DiveSite>.value(
              _FakeDiveSite_0(this, Invocation.method(#createSite, [site])),
            ),
          )
          as _i8.Future<_i2.DiveSite>);

  @override
  _i8.Future<void> updateSite(_i2.DiveSite? site) =>
      (super.noSuchMethod(
            Invocation.method(#updateSite, [site]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> applyImportedMetadata(
    String? siteId,
    _i9.DiveSitesCompanion? patch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyImportedMetadata, [siteId, patch]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setShared(String? id, bool? isShared) =>
      (super.noSuchMethod(
            Invocation.method(#setShared, [id, isShared]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> shareAllForDiver(String? diverId) =>
      (super.noSuchMethod(
            Invocation.method(#shareAllForDiver, [diverId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> deleteSite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSite, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.DiveSite>> getSitesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getSitesByIds, [ids]),
            returnValue: _i8.Future<List<_i2.DiveSite>>.value(<_i2.DiveSite>[]),
          )
          as _i8.Future<List<_i2.DiveSite>>);

  @override
  _i8.Future<void> bulkDeleteSites(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteSites, [ids]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i7.MergeSnapshot?> mergeSites({
    required _i2.DiveSite? mergedSite,
    required List<String>? siteIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeSites, [], {
              #mergedSite: mergedSite,
              #siteIds: siteIds,
            }),
            returnValue: _i8.Future<_i7.MergeSnapshot?>.value(),
          )
          as _i8.Future<_i7.MergeSnapshot?>);

  @override
  _i8.Future<void> undoMerge(_i7.MergeSnapshot? snapshot) =>
      (super.noSuchMethod(
            Invocation.method(#undoMerge, [snapshot]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.DiveSite>> searchSites(
    String? query, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchSites, [query], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i2.DiveSite>>.value(<_i2.DiveSite>[]),
          )
          as _i8.Future<List<_i2.DiveSite>>);

  @override
  _i8.Future<Map<String, int>> getDiveCountsBySite() =>
      (super.noSuchMethod(
            Invocation.method(#getDiveCountsBySite, []),
            returnValue: _i8.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i8.Future<Map<String, int>>);

  @override
  _i8.Future<List<_i7.SiteWithDiveCount>> getSitesWithDiveCounts({
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSitesWithDiveCounts, [], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i7.SiteWithDiveCount>>.value(
              <_i7.SiteWithDiveCount>[],
            ),
          )
          as _i8.Future<List<_i7.SiteWithDiveCount>>);
}

/// A class which mocks [DiveSiteApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveSiteApiService extends _i1.Mock
    implements _i3.DiveSiteApiService {
  MockDiveSiteApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.DiveSiteSearchResult> searchSites(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchSites, [query]),
            returnValue: _i8.Future<_i3.DiveSiteSearchResult>.value(
              _FakeDiveSiteSearchResult_1(
                this,
                Invocation.method(#searchSites, [query]),
              ),
            ),
          )
          as _i8.Future<_i3.DiveSiteSearchResult>);

  @override
  _i8.Future<_i3.DiveSiteSearchResult> searchNearby({
    required double? latitude,
    required double? longitude,
    double? radiusKm = 50.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNearby, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
            }),
            returnValue: _i8.Future<_i3.DiveSiteSearchResult>.value(
              _FakeDiveSiteSearchResult_1(
                this,
                Invocation.method(#searchNearby, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                  #radiusKm: radiusKm,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.DiveSiteSearchResult>);

  @override
  _i8.Future<_i3.DiveSiteSearchResult> searchByCountry(String? country) =>
      (super.noSuchMethod(
            Invocation.method(#searchByCountry, [country]),
            returnValue: _i8.Future<_i3.DiveSiteSearchResult>.value(
              _FakeDiveSiteSearchResult_1(
                this,
                Invocation.method(#searchByCountry, [country]),
              ),
            ),
          )
          as _i8.Future<_i3.DiveSiteSearchResult>);
}

/// A class which mocks [DiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiveRepository extends _i1.Mock implements _i5.DiveRepository {
  MockDiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<void> watchDivesChanges() =>
      (super.noSuchMethod(
            Invocation.method(#watchDivesChanges, []),
            returnValue: _i8.Stream<void>.empty(),
          )
          as _i8.Stream<void>);

  @override
  _i8.Stream<void> watchDiveDetailChanges() =>
      (super.noSuchMethod(
            Invocation.method(#watchDiveDetailChanges, []),
            returnValue: _i8.Stream<void>.empty(),
          )
          as _i8.Stream<void>);

  @override
  _i8.Future<List<_i4.Dive>> getAllDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDives, [], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<_i4.Dive?> getDiveById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveById, [id]),
            returnValue: _i8.Future<_i4.Dive?>.value(),
          )
          as _i8.Future<_i4.Dive?>);

  @override
  _i8.Future<void> setSite(String? diveId, String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#setSite, [diveId, siteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Dive>> getDivesNeedingSiteMatch({
    String? diverId,
    List<String>? limitToIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesNeedingSiteMatch, [], {
              #diverId: diverId,
              #limitToIds: limitToIds,
            }),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<List<_i4.DiveProfilePoint>> getDiveProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveProfile, [diveId]),
            returnValue: _i8.Future<List<_i4.DiveProfilePoint>>.value(
              <_i4.DiveProfilePoint>[],
            ),
          )
          as _i8.Future<List<_i4.DiveProfilePoint>>);

  @override
  _i8.Future<void> saveEditedProfile(
    String? diveId,
    List<_i4.DiveProfilePoint>? editedPoints,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditedProfile, [diveId, editedPoints]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String?, List<_i4.DiveProfilePoint>>> getProfilesBySource(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilesBySource, [diveId]),
            returnValue:
                _i8.Future<Map<String?, List<_i4.DiveProfilePoint>>>.value(
                  <String?, List<_i4.DiveProfilePoint>>{},
                ),
          )
          as _i8.Future<Map<String?, List<_i4.DiveProfilePoint>>>);

  @override
  _i8.Future<void> restoreOriginalProfile(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreOriginalProfile, [diveId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, List<_i4.DiveProfilePoint>>> getBatchProfileSummaries(
    List<String>? diveIds, {
    int? maxSamples = 120,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBatchProfileSummaries,
              [diveIds],
              {#maxSamples: maxSamples},
            ),
            returnValue:
                _i8.Future<Map<String, List<_i4.DiveProfilePoint>>>.value(
                  <String, List<_i4.DiveProfilePoint>>{},
                ),
          )
          as _i8.Future<Map<String, List<_i4.DiveProfilePoint>>>);

  @override
  _i8.Future<_i4.Dive> createDive(_i4.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#createDive, [dive]),
            returnValue: _i8.Future<_i4.Dive>.value(
              _FakeDive_2(this, Invocation.method(#createDive, [dive])),
            ),
          )
          as _i8.Future<_i4.Dive>);

  @override
  _i8.Future<void> updateDive(_i4.Dive? dive) =>
      (super.noSuchMethod(
            Invocation.method(#updateDive, [dive]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDive(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDive, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> bulkDeleteDives(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteDives, [ids]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<_i4.Dive>> getDivesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesByIds, [ids]),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<List<_i10.DiveSummary>> getDiveSummaries({
    String? diverId,
    _i11.DiveFilterState? filter = const _i11.DiveFilterState(),
    _i10.DiveSummaryCursor? cursor,
    int? offset,
    int? limit = 50,
    _i12.SortState<_i13.DiveSortField>? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveSummaries, [], {
              #diverId: diverId,
              #filter: filter,
              #cursor: cursor,
              #offset: offset,
              #limit: limit,
              #sort: sort,
            }),
            returnValue: _i8.Future<List<_i10.DiveSummary>>.value(
              <_i10.DiveSummary>[],
            ),
          )
          as _i8.Future<List<_i10.DiveSummary>>);

  @override
  _i8.Future<int> getDiveCount({
    String? diverId,
    _i11.DiveFilterState? filter = const _i11.DiveFilterState(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveCount, [], {
              #diverId: diverId,
              #filter: filter,
            }),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.Dive>> getDivesForSite(String? siteId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForSite, [siteId]),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<List<_i4.Dive>> getDivesForCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getDivesForCourse, [courseId]),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<List<_i4.Dive>> getDivesInRange(
    DateTime? start,
    DateTime? end, {
    String? diverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDivesInRange,
              [start, end],
              {#diverId: diverId},
            ),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<int> getNextDiveNumber({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextDiveNumber, [], {#diverId: diverId}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getDiveNumberForDate(
    DateTime? dateTime, {
    String? diverId,
    int? startFrom = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDiveNumberForDate,
              [dateTime],
              {#diverId: diverId, #startFrom: startFrom},
            ),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.Dive>> searchDives(String? query, {String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchDives, [query], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<_i5.DiveStatistics> getStatistics({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, [], {#diverId: diverId}),
            returnValue: _i8.Future<_i5.DiveStatistics>.value(
              _FakeDiveStatistics_3(
                this,
                Invocation.method(#getStatistics, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i8.Future<_i5.DiveStatistics>);

  @override
  _i8.Future<_i5.DiveRecords> getRecords({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecords, [], {#diverId: diverId}),
            returnValue: _i8.Future<_i5.DiveRecords>.value(
              _FakeDiveRecords_4(
                this,
                Invocation.method(#getRecords, [], {#diverId: diverId}),
              ),
            ),
          )
          as _i8.Future<_i5.DiveRecords>);

  @override
  _i8.Future<Set<String>> getImportIds({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getImportIds, [], {#diverId: diverId}),
            returnValue: _i8.Future<Set<String>>.value(<String>{}),
          )
          as _i8.Future<Set<String>>);

  @override
  _i8.Future<void> toggleFavorite(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [diveId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setFavorite(String? diveId, bool? isFavorite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorite, [diveId, isFavorite]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Dive>> getFavoriteDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteDives, [], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<List<_i4.Dive>> getPlannedDives({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPlannedDives, [], {#diverId: diverId}),
            returnValue: _i8.Future<List<_i4.Dive>>.value(<_i4.Dive>[]),
          )
          as _i8.Future<List<_i4.Dive>>);

  @override
  _i8.Future<_i4.Dive> createPlannedDive(_i4.Dive? plan) =>
      (super.noSuchMethod(
            Invocation.method(#createPlannedDive, [plan]),
            returnValue: _i8.Future<_i4.Dive>.value(
              _FakeDive_2(this, Invocation.method(#createPlannedDive, [plan])),
            ),
          )
          as _i8.Future<_i4.Dive>);

  @override
  _i8.Future<String> convertPlanToActualDive(
    String? planId, {
    DateTime? actualDateTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #convertPlanToActualDive,
              [planId],
              {#actualDateTime: actualDateTime},
            ),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #convertPlanToActualDive,
                  [planId],
                  {#actualDateTime: actualDateTime},
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deletePlannedDive(String? planId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlannedDive, [planId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.GasSwitchWithTank>> getGasSwitchesForDive(
    String? diveId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGasSwitchesForDive, [diveId]),
            returnValue: _i8.Future<List<_i6.GasSwitchWithTank>>.value(
              <_i6.GasSwitchWithTank>[],
            ),
          )
          as _i8.Future<List<_i6.GasSwitchWithTank>>);

  @override
  _i8.Future<_i6.GasSwitch> createGasSwitch(_i6.GasSwitch? gasSwitch) =>
      (super.noSuchMethod(
            Invocation.method(#createGasSwitch, [gasSwitch]),
            returnValue: _i8.Future<_i6.GasSwitch>.value(
              _FakeGasSwitch_5(
                this,
                Invocation.method(#createGasSwitch, [gasSwitch]),
              ),
            ),
          )
          as _i8.Future<_i6.GasSwitch>);

  @override
  _i8.Future<void> deleteGasSwitch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitch, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteGasSwitchesForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGasSwitchesForDive, [diveId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> insertGasSwitches(List<_i6.GasSwitch>? switches) =>
      (super.noSuchMethod(
            Invocation.method(#insertGasSwitches, [switches]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> insertProfileEvents(List<_i15.ProfileEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#insertProfileEvents, [events]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i15.ProfileEvent>> getProfileEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileEventsForDive, [diveId]),
            returnValue: _i8.Future<List<_i15.ProfileEvent>>.value(
              <_i15.ProfileEvent>[],
            ),
          )
          as _i8.Future<List<_i15.ProfileEvent>>);

  @override
  _i8.Future<void> deleteProfileEventsForDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileEventsForDive, [diveId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.Dive?> getPreviousDive(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousDive, [diveId]),
            returnValue: _i8.Future<_i4.Dive?>.value(),
          )
          as _i8.Future<_i4.Dive?>);

  @override
  _i8.Future<Duration?> getSurfaceInterval(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getSurfaceInterval, [diveId]),
            returnValue: _i8.Future<Duration?>.value(),
          )
          as _i8.Future<Duration?>);

  @override
  _i8.Future<_i5.DiveNumberingInfo> getDiveNumberingInfo({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getDiveNumberingInfo, [], {#diverId: diverId}),
            returnValue: _i8.Future<_i5.DiveNumberingInfo>.value(
              _FakeDiveNumberingInfo_6(
                this,
                Invocation.method(#getDiveNumberingInfo, [], {
                  #diverId: diverId,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.DiveNumberingInfo>);

  @override
  _i8.Future<void> renumberAllDives({int? startFrom = 1, String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#renumberAllDives, [], {
              #startFrom: startFrom,
              #diverId: diverId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> assignMissingDiveNumbers({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#assignMissingDiveNumbers, [], {
              #diverId: diverId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> bulkUpdateTrip(List<String>? diveIds, String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateTrip, [diveIds, tripId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> bulkAddTags(List<String>? diveIds, List<String>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkAddTags, [diveIds, tagIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> bulkRemoveTags(
    List<String>? diveIds,
    List<String>? tagIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bulkRemoveTags, [diveIds, tagIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i16.DiveDataSource>> getDataSources(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#getDataSources, [diveId]),
            returnValue: _i8.Future<List<_i16.DiveDataSource>>.value(
              <_i16.DiveDataSource>[],
            ),
          )
          as _i8.Future<List<_i16.DiveDataSource>>);

  @override
  _i8.Future<Map<String, String>> getSourceUuidByDiveId({String? diverId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSourceUuidByDiveId, [], {#diverId: diverId}),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<bool> hasMultipleDataSources(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#hasMultipleDataSources, [diveId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> applyImportedMetadata(
    String? diveId,
    _i9.DivesCompanion? patch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyImportedMetadata, [diveId, patch]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> saveComputerReading(_i9.DiveDataSourcesCompanion? reading) =>
      (super.noSuchMethod(
            Invocation.method(#saveComputerReading, [reading]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteComputerReading(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComputerReading, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> backfillPrimaryDataSource(String? diveId) =>
      (super.noSuchMethod(
            Invocation.method(#backfillPrimaryDataSource, [diveId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> consolidateComputer({
    required String? targetDiveId,
    required _i9.DiveDataSourcesCompanion? secondaryReading,
    required List<_i9.DiveProfilesCompanion>? secondaryProfile,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#consolidateComputer, [], {
              #targetDiveId: targetDiveId,
              #secondaryReading: secondaryReading,
              #secondaryProfile: secondaryProfile,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> mergeDives({
    required String? primaryDiveId,
    required String? secondaryDiveId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeDives, [], {
              #primaryDiveId: primaryDiveId,
              #secondaryDiveId: secondaryDiveId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> unlinkComputer({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkComputer, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#unlinkComputer, [], {
                  #diveId: diveId,
                  #computerReadingId: computerReadingId,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> setPrimaryDataSource({
    required String? diveId,
    required String? computerReadingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryDataSource, [], {
              #diveId: diveId,
              #computerReadingId: computerReadingId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
