import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/services.dart' show rootBundle;

/// A NOAA harmonic station near a queried coordinate.
class NearbyStation {
  final String id;
  final String name;
  final double latitude;
  final double longitude;
  final double distanceKm;

  const NearbyStation({
    required this.id,
    required this.name,
    required this.latitude,
    required this.longitude,
    required this.distanceKm,
  });
}

/// In-memory index of NOAA CO-OPS harmonic stations, loaded from the
/// bundled asset generated by scripts/tide/generate_noaa_station_index.py.
class NoaaStationIndex {
  final List<List<dynamic>> _rows;

  NoaaStationIndex(this._rows);

  factory NoaaStationIndex.fromJsonString(String s) {
    return NoaaStationIndex((json.decode(s) as List).cast<List<dynamic>>());
  }

  static Future<NoaaStationIndex> load() async {
    final s = await rootBundle.loadString(
      'assets/data/tide/noaa_stations.json',
    );
    return NoaaStationIndex.fromJsonString(s);
  }

  /// Nearest station within [maxKm] of the coordinate, or null.
  NearbyStation? nearest(
    double latitude,
    double longitude, {
    double maxKm = 25.0,
  }) {
    NearbyStation? best;
    for (final row in _rows) {
      final lat = (row[2] as num).toDouble();
      final lon = (row[3] as num).toDouble();
      final d = _haversineKm(latitude, longitude, lat, lon);
      if (d <= maxKm && (best == null || d < best.distanceKm)) {
        best = NearbyStation(
          id: row[0] as String,
          name: row[1] as String,
          latitude: lat,
          longitude: lon,
          distanceKm: d,
        );
      }
    }
    return best;
  }

  static double _haversineKm(
    double lat1,
    double lon1,
    double lat2,
    double lon2,
  ) {
    const r = 6371.0;
    final dLat = _rad(lat2 - lat1);
    final dLon = _rad(lon2 - lon1);
    final a =
        math.sin(dLat / 2) * math.sin(dLat / 2) +
        math.cos(_rad(lat1)) *
            math.cos(_rad(lat2)) *
            math.sin(dLon / 2) *
            math.sin(dLon / 2);
    return 2 * r * math.asin(math.min(1.0, math.sqrt(a)));
  }

  static double _rad(double deg) => deg * math.pi / 180.0;
}
