#!/usr/bin/env python3
"""Generate lib/core/util/tz_lookup_data.dart from photostructure/tz-lookup.

tz-lookup (CC0-1.0) maps a coordinate to an IANA zone id with a compact
quadtree. This script downloads tz.js at a pinned commit, checks that the
decoder constants still match the Dart port in
lib/core/util/site_time_zone.dart, and writes the quadtree string and zone
list as Dart constants.

Usage (from the repo root):
    python3.14 scripts/tide/generate_tz_lookup_data.py
"""

import json
import re
import urllib.request
from pathlib import Path

COMMIT = "6051e7e2fe8b754e23d40aff0120cf9b38bde608"
URL = f"https://raw.githubusercontent.com/photostructure/tz-lookup/{COMMIT}/tz.js"
OUT = Path("lib/core/util/tz_lookup_data.dart")

# Constants baked into the Dart decoder. If upstream changes any of them the
# port must change too, so fail loudly instead of emitting mismatched data.
REQUIRED_SNIPPETS = [
    "48*(180+W)/360.00000000000006",
    "24*(90-Y)/180.00000000000003",
    "K=96*$+2*Z",
    "-1995",
    "K+T.length<3136",
    "+2304)",
]


def extract_js_string(src: str, start: int) -> tuple[str, int]:
    """Decode the double-quoted JS string literal that starts at src[start]."""
    if src[start] != '"':
        raise SystemExit("tz.js changed: data string not found")
    end = start + 1
    while src[end] != '"':
        end += 2 if src[end] == "\\" else 1
    return json.loads(src[start : end + 1]), end + 1


def dart_literal(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$")
    return "'" + escaped + "'"


def main() -> None:
    req = urllib.request.Request(URL, headers={"User-Agent": "submersion"})
    with urllib.request.urlopen(req, timeout=60) as response:
        src = response.read().decode("utf-8")

    for snippet in REQUIRED_SNIPPETS:
        if snippet not in src:
            raise SystemExit(f"tz.js changed: missing decoder snippet {snippet!r}")

    data, after = extract_js_string(src, src.index('var X="') + len("var X="))
    zones_match = re.search(r"T=(\[[^\]]*\])", src[after:])
    if zones_match is None:
        raise SystemExit("tz.js changed: zone list not found")
    zones = json.loads(zones_match.group(1))
    if any(not (32 <= ord(ch) < 127) for ch in data):
        raise SystemExit("tz.js data has non-printable characters")
    if any("|" in zone for zone in zones):
        raise SystemExit("a zone id contains the '|' separator")

    # Long chunks keep the file well under the repo's 800-line limit.
    chunks = [data[i : i + 200] for i in range(0, len(data), 200)]
    joined = "|".join(zones)
    zone_chunks = [joined[i : i + 200] for i in range(0, len(joined), 200)]
    lines = [
        "// GENERATED by scripts/tide/generate_tz_lookup_data.py. Do not edit.",
        "//",
        "// Quadtree and zone list from photostructure/tz-lookup at commit",
        f"// {COMMIT}.",
        "// The upstream authors released this data under CC0-1.0.",
        "",
        "/// Quadtree nodes: pairs of characters read as base-56 integers.",
        "const String tzLookupData =",
        *[f"    {dart_literal(chunk)}" for chunk in chunks[:-1]],
        f"    {dart_literal(chunks[-1])};",
        "",
        "/// IANA zone ids addressed by the quadtree leaves, '|'-separated.",
        "const String _tzLookupZonesJoined =",
        *[f"    {dart_literal(chunk)}" for chunk in zone_chunks[:-1]],
        f"    {dart_literal(zone_chunks[-1])};",
        "",
        "/// IANA zone ids addressed by the quadtree leaves.",
        "final List<String> tzLookupZones = List.unmodifiable(",
        "  _tzLookupZonesJoined.split('|'),",
        ");",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(data)} data chars and {len(zones)} zones to {OUT}")


if __name__ == "__main__":
    main()
