#!/usr/bin/env python3
"""Fetches the EFF short wordlist (1296 words) and emits a Dart constant.

Output: lib/core/services/sync/crypto/eff_short_wordlist.dart
"""
import urllib.request

URL = "https://www.eff.org/files/2016/09/08/eff_short_wordlist_1.txt"

raw = urllib.request.urlopen(URL).read().decode()
words = []
for line in raw.strip().splitlines():
    # lines look like: "1111\tacid"
    parts = line.split()
    words.append(parts[-1])
assert len(words) == 1296, f"expected 1296 words, got {len(words)}"
assert len(set(words)) == 1296, "duplicate words"

with open("lib/core/services/sync/crypto/eff_short_wordlist.dart", "w") as f:
    f.write("/// EFF short wordlist #1 (1296 words), for recovery codes.\n")
    f.write("/// Generated by scripts/generate_eff_wordlist.py. Do not edit.\n")
    f.write("/// Source: https://www.eff.org/dice\n")
    f.write("const List<String> effShortWordlist = [\n")
    for w in words:
        f.write(f"  '{w}',\n")
    f.write("];\n")
print("wrote eff_short_wordlist.dart with", len(words), "words")
