import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:submersion/core/deco/vpm_b_algorithm.dart';

/// Validates the Dart VPM-B port against golden vectors generated by the
/// independent BSD-2 `bwaite/vpmb` reference engine. The vectors are the
/// acceptance contract: regenerate them with scripts/deco_golden/vpmb_generate.py,
/// never hand-edit test/core/deco/golden/vpmb_golden.json.
void main() {
  final goldenFile = File('test/core/deco/golden/vpmb_golden.json');
  final golden =
      jsonDecode(goldenFile.readAsStringSync()) as Map<String, dynamic>;

  /// Rebuild the dive inputs exactly as the generator's `dive()` helper does:
  /// a descent 0 -> depth at 18 msw/min, a constant leg to [bottomMin], then a
  /// single-change ascent at 10 msw/min in 3 msw steps.
  List<VpmStop> schedule(
    int level, {
    required double depthM,
    required double bottomMin,
    double o2 = 0.21,
    double he = 0.0,
    double descentRate = 18.0,
    double ascentRate = 10.0,
  }) {
    final n2 = double.parse((1.0 - o2 - he).toStringAsFixed(6));
    final algo = VpmBAlgorithm(VpmBSettings.forConservatism(level));
    return algo.computeDive(
      gasMixes: [VpmGasMix(fN2: n2, fHe: he)],
      profile: [
        VpmDepthChangeSegment(
          startingDepth: 0,
          endingDepth: depthM,
          rate: descentRate,
          mixNumber: 1,
        ),
        VpmConstantSegment(
          depth: depthM,
          runTimeAtEndOfSegment: bottomMin,
          mixNumber: 1,
        ),
      ],
      ascentChanges: [
        VpmAscentChange(
          startingDepth: depthM,
          mixNumber: 1,
          rate: -ascentRate,
          stepSize: 3,
        ),
      ],
    );
  }

  List<List<int>> toPairs(List<VpmStop> stops) => [
    for (final s in stops) [s.depth, s.time],
  ];

  List<List<int>> goldenPairs(List<dynamic> rows) => [
    for (final r in rows) [(r as List)[0] as int, r[1] as int],
  ];

  for (final entry in golden.entries) {
    final name = entry.key;
    final data = entry.value as Map<String, dynamic>;
    final dive = data['dive'] as Map<String, dynamic>;
    final schedules = data['schedules'] as Map<String, dynamic>;

    final depthM = (dive['depth_m'] as num).toDouble();
    final bottomMin = (dive['bottom_min'] as num).toDouble();
    final o2 = (dive['o2'] as num?)?.toDouble() ?? 0.21;
    final he = (dive['he'] as num?)?.toDouble() ?? 0.0;

    group('VPM-B golden: $name', () {
      for (final lvl in schedules.keys) {
        final expected = goldenPairs(schedules[lvl] as List<dynamic>);
        test('conservatism +$lvl', () {
          final actual = toPairs(
            schedule(
              int.parse(lvl),
              depthM: depthM,
              bottomMin: bottomMin,
              o2: o2,
              he: he,
            ),
          );
          expect(actual, equals(expected));
        });
      }
    });
  }

  test('air 50m/25min +3 first stop is 27 m (research tripwire)', () {
    final stops = schedule(3, depthM: 50, bottomMin: 25);
    expect(stops.first.depth, 27);
  });
}
