import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:submersion/core/constants/enums.dart';
import 'package:submersion/core/icons/mdi_icons.dart';
import 'package:submersion/core/icons/submersion_icons.dart';
import 'package:submersion/features/equipment/presentation/utils/equipment_type_icon.dart';

/// Proves every glyph the app asks a *vendored* font for actually exists in
/// the committed `.ttf`.
///
/// Nothing else does. Asserting an [IconData]'s `fontFamily` only checks a
/// string, and a code point the font never mapped renders as an empty box on
/// a device while every test stays green. Two real ways that happens here:
///
/// - [MdiIcons] code points are transcribed by hand from the Material Design
///   Icons release notes. A digit typed wrong compiles, analyzes and passes
///   every other test.
/// - The [SubmersionIcons] font is generated by `tool/build_equipment_icon_font.py`
///   and has to be re-run and re-committed by hand. A glyph added to
///   `tool/equipment_glyphs.py` without that rebuild is a constant pointing
///   into an unmapped code point.
///
/// Only the two fonts this repo ships are checked. `Icons.*` comes from
/// Flutter's own MaterialIcons font, which is not ours to vouch for.
void main() {
  const vendored = <String, String>{
    SubmersionIcons.fontFamily: 'assets/fonts/submersion-equipment.ttf',
    MdiIcons.fontFamily: 'assets/fonts/materialdesignicons-webfont.ttf',
  };

  final cmaps = <String, _Cmap>{
    for (final entry in vendored.entries)
      entry.key: _Cmap.fromFile(File(entry.value)),
  };

  test('both vendored fonts are present and parse', () {
    for (final entry in vendored.entries) {
      expect(
        File(entry.value).existsSync(),
        isTrue,
        reason: '${entry.value} is declared in pubspec.yaml but not committed',
      );
      expect(
        cmaps[entry.key]!.isEmpty,
        isFalse,
        reason: '${entry.value} has no usable Unicode cmap subtable',
      );
    }
  });

  test('every equipment glyph resolves in the font it names', () {
    final missing = <String>[];
    for (final type in EquipmentType.values) {
      final icon = equipmentTypeIcon(type);
      final cmap = cmaps[icon.fontFamily];
      // Material's own font is Flutter's to guarantee, not ours.
      if (cmap == null) continue;
      if (!cmap.maps(icon.codePoint)) {
        missing.add(
          '${type.name}: U+${icon.codePoint.toRadixString(16).toUpperCase()} '
          'is not mapped by ${icon.fontFamily}',
        );
      }
    }
    expect(missing, isEmpty, reason: missing.join('\n'));
  });

  test('the drawn glyph font maps every constant, not just the used ones', () {
    // `SubmersionIcons` is small and entirely ours, so it is checked whole:
    // a constant added ahead of the font rebuild fails here even before an
    // equipment type points at it.
    const drawn = <String, IconData>{
      'wetsuit': SubmersionIcons.wetsuit,
      'gloves': SubmersionIcons.gloves,
      'boots': SubmersionIcons.boots,
      'drysuit': SubmersionIcons.drysuit,
      'regulator': SubmersionIcons.regulator,
      'bcd': SubmersionIcons.bcd,
      'rebreather': SubmersionIcons.rebreather,
      'hood': SubmersionIcons.hood,
      'reel': SubmersionIcons.reel,
      'dpv': SubmersionIcons.dpv,
      'undergarment': SubmersionIcons.undergarment,
    };
    final cmap = cmaps[SubmersionIcons.fontFamily]!;
    for (final entry in drawn.entries) {
      expect(
        cmap.maps(entry.value.codePoint),
        isTrue,
        reason:
            '${entry.key} points at U+'
            '${entry.value.codePoint.toRadixString(16).toUpperCase()}, which '
            'the committed font does not map. Re-run '
            'tool/build_equipment_icon_font.py and commit the .ttf.',
      );
    }
  });

  test('a code point the fonts do not have is reported as missing', () {
    // Guards the parser itself: a `maps` that answered true for everything
    // would make all of the above vacuous.
    for (final cmap in cmaps.values) {
      expect(cmap.maps(0x0E0FFF), isFalse);
    }
    // And one it does have, so a `maps` that answered false for everything
    // could not hide either.
    expect(cmaps[SubmersionIcons.fontFamily]!.maps(0xE900), isTrue);
    expect(
      cmaps[MdiIcons.fontFamily]!.maps(MdiIcons.compass.codePoint),
      isTrue,
    );
  });
}

/// The Unicode character-to-glyph subtables of one TrueType font, queried one
/// code point at a time.
///
/// Only the two subtable formats the vendored fonts use are understood:
/// format 4 for the BMP (the Submersion font's private-use range) and format
/// 12 for the supplementary planes (Material Design Icons lives in Plane 15).
class _Cmap {
  _Cmap._(this._data, this._subtables);

  final ByteData _data;
  final List<int> _subtables;

  bool get isEmpty => _subtables.isEmpty;

  static _Cmap fromFile(File file) {
    if (!file.existsSync()) return _Cmap._(ByteData(0), const []);
    final data = ByteData.sublistView(file.readAsBytesSync());
    final tableCount = data.getUint16(4);
    int? cmapOffset;
    for (var i = 0; i < tableCount; i++) {
      final record = 12 + i * 16;
      final tag = String.fromCharCodes([
        for (var b = 0; b < 4; b++) data.getUint8(record + b),
      ]);
      if (tag == 'cmap') {
        cmapOffset = data.getUint32(record + 8);
        break;
      }
    }
    if (cmapOffset == null) return _Cmap._(data, const []);

    final subtables = <int>[];
    final encodingCount = data.getUint16(cmapOffset + 2);
    for (var i = 0; i < encodingCount; i++) {
      final record = cmapOffset + 4 + i * 8;
      final platformId = data.getUint16(record);
      final encodingId = data.getUint16(record + 2);
      // Unicode (platform 0) or Windows BMP/full-repertoire (3/1, 3/10).
      final isUnicode =
          platformId == 0 ||
          (platformId == 3 && (encodingId == 1 || encodingId == 10));
      if (!isUnicode) continue;
      final offset = cmapOffset + data.getUint32(record + 4);
      final format = data.getUint16(offset);
      if (format == 4 || format == 12) subtables.add(offset);
    }
    return _Cmap._(data, subtables);
  }

  /// Whether [codePoint] maps to a real (non-zero) glyph in any subtable.
  bool maps(int codePoint) {
    for (final offset in _subtables) {
      final found = switch (_data.getUint16(offset)) {
        4 => _mapsFormat4(offset, codePoint),
        12 => _mapsFormat12(offset, codePoint),
        _ => false,
      };
      if (found) return true;
    }
    return false;
  }

  bool _mapsFormat4(int sub, int codePoint) {
    if (codePoint > 0xFFFF) return false;
    final segCount = _data.getUint16(sub + 6) ~/ 2;
    final endCodes = sub + 14;
    final startCodes = endCodes + segCount * 2 + 2;
    final idDeltas = startCodes + segCount * 2;
    final idRangeOffsets = idDeltas + segCount * 2;
    for (var s = 0; s < segCount; s++) {
      final end = _data.getUint16(endCodes + s * 2);
      if (codePoint > end) continue;
      final start = _data.getUint16(startCodes + s * 2);
      if (codePoint < start) return false; // Segments are sorted.
      final delta = _data.getInt16(idDeltas + s * 2);
      final rangeOffset = _data.getUint16(idRangeOffsets + s * 2);
      if (rangeOffset == 0) return (codePoint + delta) & 0xFFFF != 0;
      final glyphAt =
          idRangeOffsets + s * 2 + rangeOffset + (codePoint - start) * 2;
      if (glyphAt + 1 >= _data.lengthInBytes) return false;
      return _data.getUint16(glyphAt) != 0;
    }
    return false;
  }

  bool _mapsFormat12(int sub, int codePoint) {
    final groupCount = _data.getUint32(sub + 12);
    for (var g = 0; g < groupCount; g++) {
      final record = sub + 16 + g * 12;
      final start = _data.getUint32(record);
      if (codePoint < start) return false; // Groups are sorted.
      if (codePoint <= _data.getUint32(record + 4)) return true;
    }
    return false;
  }
}
