// Mocks generated by Mockito 5.4.6 from annotations
// in submersion/test/features/media/data/services/asset_resolution_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:submersion/features/media/data/repositories/local_asset_cache_repository.dart'
    as _i2;
import 'package:submersion/features/media/data/services/photo_picker_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalAssetCacheRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAssetCacheRepository extends _i1.Mock
    implements _i2.LocalAssetCacheRepository {
  MockLocalAssetCacheRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getCachedAssetId(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAssetId, [mediaId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i2.CacheEntry?> getCacheEntry(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#getCacheEntry, [mediaId]),
            returnValue: _i3.Future<_i2.CacheEntry?>.value(),
          )
          as _i3.Future<_i2.CacheEntry?>);

  @override
  _i3.Future<void> cacheResolution({
    required String? mediaId,
    required String? localAssetId,
    required String? method,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheResolution, [], {
              #mediaId: mediaId,
              #localAssetId: localAssetId,
              #method: method,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearEntry(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#clearEntry, [mediaId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isExpired(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#isExpired, [mediaId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> incrementAttempt(String? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementAttempt, [mediaId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PhotoPickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoPickerService extends _i1.Mock
    implements _i4.PhotoPickerService {
  MockPhotoPickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get supportsGalleryBrowsing =>
      (super.noSuchMethod(
            Invocation.getter(#supportsGalleryBrowsing),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<List<_i4.AssetInfo>> getAssetsInDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetsInDateRange, [start, end]),
            returnValue: _i3.Future<List<_i4.AssetInfo>>.value(
              <_i4.AssetInfo>[],
            ),
          )
          as _i3.Future<List<_i4.AssetInfo>>);

  @override
  _i3.Future<_i5.Uint8List?> getThumbnail(String? assetId, {int? size = 200}) =>
      (super.noSuchMethod(
            Invocation.method(#getThumbnail, [assetId], {#size: size}),
            returnValue: _i3.Future<_i5.Uint8List?>.value(),
          )
          as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<_i5.Uint8List?> getFileBytes(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#getFileBytes, [assetId]),
            returnValue: _i3.Future<_i5.Uint8List?>.value(),
          )
          as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<_i4.PhotoPermissionStatus> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i3.Future<_i4.PhotoPermissionStatus>.value(
              _i4.PhotoPermissionStatus.authorized,
            ),
          )
          as _i3.Future<_i4.PhotoPermissionStatus>);

  @override
  _i3.Future<_i4.PhotoPermissionStatus> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<_i4.PhotoPermissionStatus>.value(
              _i4.PhotoPermissionStatus.authorized,
            ),
          )
          as _i3.Future<_i4.PhotoPermissionStatus>);

  @override
  _i3.Future<String?> getFilePath(String? assetId) =>
      (super.noSuchMethod(
            Invocation.method(#getFilePath, [assetId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
