import 'package:submersion/core/constants/dive_field.dart';

/// Extension providing default and minimum column widths for each [DiveField].
extension DiveFieldColumnSizing on DiveField {
  /// Default column width in logical pixels.
  double get defaultWidth {
    switch (this) {
      case DiveField.diveNumber:
        return 60;
      case DiveField.dateTime:
        return 160;
      case DiveField.siteName:
        return 160;
      case DiveField.maxDepth:
        return 80;
      case DiveField.avgDepth:
        return 80;
      case DiveField.bottomTime:
        return 80;
      case DiveField.runtime:
        return 80;
      case DiveField.waterTemp:
        return 90;
      case DiveField.airTemp:
        return 90;
      case DiveField.visibility:
        return 100;
      case DiveField.currentDirection:
        return 100;
      case DiveField.currentStrength:
        return 100;
      case DiveField.swellHeight:
        return 80;
      case DiveField.entryMethod:
        return 100;
      case DiveField.exitMethod:
        return 100;
      case DiveField.waterType:
        return 90;
      case DiveField.altitude:
        return 90;
      case DiveField.surfacePressure:
        return 90;
      case DiveField.windSpeed:
        return 90;
      case DiveField.cloudCover:
        return 100;
      case DiveField.precipitation:
        return 100;
      case DiveField.humidity:
        return 80;
      case DiveField.weatherDescription:
        return 140;
      case DiveField.primaryGas:
        return 80;
      case DiveField.diluentGas:
        return 80;
      case DiveField.tankCount:
        return 70;
      case DiveField.startPressure:
        return 90;
      case DiveField.endPressure:
        return 90;
      case DiveField.sacRate:
        return 80;
      case DiveField.gasConsumed:
        return 100;
      case DiveField.totalWeight:
        return 80;
      case DiveField.diveComputerModel:
        return 140;
      case DiveField.gradientFactorLow:
        return 70;
      case DiveField.gradientFactorHigh:
        return 70;
      case DiveField.decoAlgorithm:
        return 100;
      case DiveField.decoConservatism:
        return 90;
      case DiveField.cnsStart:
        return 90;
      case DiveField.cnsEnd:
        return 90;
      case DiveField.otu:
        return 70;
      case DiveField.diveMode:
        return 80;
      case DiveField.setpointLow:
        return 80;
      case DiveField.setpointHigh:
        return 80;
      case DiveField.setpointDeco:
        return 90;
      case DiveField.buddy:
        return 120;
      case DiveField.diveMaster:
        return 120;
      case DiveField.siteLocation:
        return 160;
      case DiveField.diveCenterName:
        return 140;
      case DiveField.siteLatitude:
        return 100;
      case DiveField.siteLongitude:
        return 100;
      case DiveField.tripName:
        return 140;
      case DiveField.ratingStars:
        return 80;
      case DiveField.isFavorite:
        return 60;
      case DiveField.notes:
        return 200;
      case DiveField.tags:
        return 160;
      case DiveField.importSource:
        return 100;
      case DiveField.diveTypeName:
        return 100;
      case DiveField.surfaceInterval:
        return 80;
    }
  }

  /// Minimum column width in logical pixels. Always <= defaultWidth.
  double get minWidth {
    switch (this) {
      case DiveField.diveNumber:
        return 40;
      case DiveField.dateTime:
        return 80;
      case DiveField.siteName:
        return 60;
      case DiveField.maxDepth:
        return 60;
      case DiveField.avgDepth:
        return 60;
      case DiveField.bottomTime:
        return 60;
      case DiveField.runtime:
        return 60;
      case DiveField.waterTemp:
        return 60;
      case DiveField.airTemp:
        return 60;
      case DiveField.visibility:
        return 60;
      case DiveField.currentDirection:
        return 60;
      case DiveField.currentStrength:
        return 60;
      case DiveField.swellHeight:
        return 60;
      case DiveField.entryMethod:
        return 60;
      case DiveField.exitMethod:
        return 60;
      case DiveField.waterType:
        return 60;
      case DiveField.altitude:
        return 60;
      case DiveField.surfacePressure:
        return 60;
      case DiveField.windSpeed:
        return 60;
      case DiveField.cloudCover:
        return 60;
      case DiveField.precipitation:
        return 60;
      case DiveField.humidity:
        return 60;
      case DiveField.weatherDescription:
        return 80;
      case DiveField.primaryGas:
        return 60;
      case DiveField.diluentGas:
        return 60;
      case DiveField.tankCount:
        return 50;
      case DiveField.startPressure:
        return 60;
      case DiveField.endPressure:
        return 60;
      case DiveField.sacRate:
        return 60;
      case DiveField.gasConsumed:
        return 60;
      case DiveField.totalWeight:
        return 60;
      case DiveField.diveComputerModel:
        return 80;
      case DiveField.gradientFactorLow:
        return 50;
      case DiveField.gradientFactorHigh:
        return 50;
      case DiveField.decoAlgorithm:
        return 60;
      case DiveField.decoConservatism:
        return 60;
      case DiveField.cnsStart:
        return 60;
      case DiveField.cnsEnd:
        return 60;
      case DiveField.otu:
        return 50;
      case DiveField.diveMode:
        return 60;
      case DiveField.setpointLow:
        return 60;
      case DiveField.setpointHigh:
        return 60;
      case DiveField.setpointDeco:
        return 60;
      case DiveField.buddy:
        return 60;
      case DiveField.diveMaster:
        return 60;
      case DiveField.siteLocation:
        return 80;
      case DiveField.diveCenterName:
        return 80;
      case DiveField.siteLatitude:
        return 60;
      case DiveField.siteLongitude:
        return 60;
      case DiveField.tripName:
        return 60;
      case DiveField.ratingStars:
        return 60;
      case DiveField.isFavorite:
        return 40;
      case DiveField.notes:
        return 80;
      case DiveField.tags:
        return 60;
      case DiveField.importSource:
        return 60;
      case DiveField.diveTypeName:
        return 60;
      case DiveField.surfaceInterval:
        return 60;
    }
  }
}
