/// English short names for the ISO 3166-1 alpha-2 codes the bundled
/// emergency data uses (hotline regions, EMS numbers and chambers), for the
/// emergency card's region picker (issue #3091).
///
/// Reference data, like the site country list. A test fails when the bundled
/// data gains a code this table does not name.
const Map<String, String> emergencyCountryNames = {
  'AE': 'United Arab Emirates',
  'AR': 'Argentina',
  'AT': 'Austria',
  'AU': 'Australia',
  'BE': 'Belgium',
  'BM': 'Bermuda',
  'BQ': 'Caribbean Netherlands',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BZ': 'Belize',
  'CA': 'Canada',
  'CH': 'Switzerland',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DK': 'Denmark',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'ES': 'Spain',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FM': 'Micronesia',
  'FR': 'France',
  'GB': 'United Kingdom',
  'GD': 'Grenada',
  'GR': 'Greece',
  'HK': 'Hong Kong',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IN': 'India',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KH': 'Cambodia',
  'KR': 'South Korea',
  'KY': 'Cayman Islands',
  'LK': 'Sri Lanka',
  'LU': 'Luxembourg',
  'MH': 'Marshall Islands',
  'MM': 'Myanmar',
  'MT': 'Malta',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MZ': 'Mozambique',
  'NA': 'Namibia',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NZ': 'New Zealand',
  'PA': 'Panama',
  'PE': 'Peru',
  'PF': 'French Polynesia',
  'PG': 'Papua New Guinea',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PR': 'Puerto Rico',
  'PT': 'Portugal',
  'PW': 'Palau',
  'SA': 'Saudi Arabia',
  'SC': 'Seychelles',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'TC': 'Turks and Caicos Islands',
  'TH': 'Thailand',
  'TR': 'Turkey',
  'TT': 'Trinidad and Tobago',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'US': 'United States',
  'UY': 'Uruguay',
  'VE': 'Venezuela',
  'VI': 'U.S. Virgin Islands',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'ZA': 'South Africa',
};

/// "Germany (DE)" for a code the table names, else the code itself, so an
/// override synced from a newer build still reads as something.
String emergencyRegionDisplayName(String code) {
  final name = emergencyCountryNames[code];
  return name == null ? code : '$name ($code)';
}
